defmodule Magus.MailTest do
  @moduledoc """
  Tests for `Magus.Mail` — the centralized module for sending transactional
  emails with in-repo rendered HTML + plain-text bodies.

  Covers:
  - All 8 public email functions
  - `send_mail_verification_to/3` for override email
  - Locale selection (DE vs EN copy)
  - html_body / text_body presence and content (action_url, name)
  - Subject presence and absence of legacy Postmark template provider options
  - Handling plain email string input (no user struct)
  - Handling nil display_name
  - Support request confirmation + notification
  """
  use Magus.ResourceCase, async: true

  import Swoosh.TestAssertions

  alias Magus.Mail

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  # Drain any emails sent during setup (e.g., user registration confirmation).
  defp drain_mailbox do
    receive do
      {:email, _} -> drain_mailbox()
    after
      0 -> :ok
    end
  end

  # Asserts the email has no legacy Postmark template provider options.
  # Returns `:ok` so it can be the final expression of an `assert_email_sent`
  # callback (a `refute` returns `false`, which the callback treats as failure).
  defp refute_template_options(email) do
    refute Map.has_key?(email.provider_options, :template_id)
    refute Map.has_key?(email.provider_options, :template_model)
    :ok
  end

  # ---------------------------------------------------------------------------
  # Setup
  # ---------------------------------------------------------------------------

  setup do
    en_user = generate(user(display_name: "Alice", language: :en))
    de_user = generate(user(display_name: "Bob", language: :de))

    # Drain confirmation emails generated by user registration
    drain_mailbox()

    %{en_user: en_user, de_user: de_user}
  end

  # ---------------------------------------------------------------------------
  # send_magic_link/2
  # ---------------------------------------------------------------------------

  describe "send_magic_link/2" do
    test "renders English body for EN user", %{en_user: user} do
      url = "https://magus.digital/magic_link/abc"
      assert {:ok, _} = Mail.send_magic_link(user, url)

      assert_email_sent(fn email ->
        assert [{"", to_email}] = email.to
        assert to_email == to_string(user.email)

        assert email.subject != nil and email.subject != ""
        assert email.subject =~ "sign-in link"

        assert email.html_body != nil
        assert email.text_body != nil

        # English phrase + CTA label
        assert email.html_body =~ "Sign in to Magus"
        assert email.text_body =~ "Sign in to Magus"

        # name and action_url present in both bodies
        assert email.html_body =~ "Alice"
        assert email.text_body =~ "Alice"
        assert email.html_body =~ url
        assert email.text_body =~ url

        refute_template_options(email)
      end)
    end

    test "renders German body for DE user", %{de_user: user} do
      url = "https://magus.digital/magic_link/xyz"
      assert {:ok, _} = Mail.send_magic_link(user, url)

      assert_email_sent(fn email ->
        assert email.subject =~ "Anmeldelink"

        # German phrase + informal CTA
        assert email.html_body =~ "Bei Magus anmelden"
        assert email.text_body =~ "Bei Magus anmelden"

        assert email.html_body =~ "Bob"
        assert email.html_body =~ url
        assert email.text_body =~ url

        refute_template_options(email)
      end)
    end

    test "handles plain email string (no user struct), empty name, EN" do
      url = "https://example.com/link"
      assert {:ok, _} = Mail.send_magic_link("new@example.com", url)

      assert_email_sent(fn email ->
        assert [{"", "new@example.com"}] = email.to

        # EN fallback copy
        assert email.html_body =~ "Sign in to Magus"
        # Empty name renders a clean greeting (no trailing name)
        assert email.html_body =~ "Hi,"
        assert email.text_body =~ "Hi,"
        assert email.html_body =~ url
      end)
    end

    test "handles user with nil display_name (renders empty name, no crash)" do
      user = generate(user(display_name: nil, language: :en))
      drain_mailbox()

      assert {:ok, _} = Mail.send_magic_link(user, "https://example.com/link")

      assert_email_sent(fn email ->
        # No leftover name fragment; greeting falls back cleanly
        assert email.html_body =~ "Hi,"
        assert email.text_body =~ "Hi,"
      end)
    end

    test "includes message_stream provider option", %{en_user: user} do
      assert {:ok, _} = Mail.send_magic_link(user, "https://example.com/link")

      assert_email_sent(fn email ->
        assert email.provider_options.message_stream == "outbound"
      end)
    end

    test "sends from Magus", %{en_user: user} do
      assert {:ok, _} = Mail.send_magic_link(user, "https://example.com/link")

      assert_email_sent(fn email ->
        assert email.from == {"Magus", "support@magus.digital"}
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_mail_verification/2
  # ---------------------------------------------------------------------------

  describe "send_mail_verification/2" do
    test "renders EN body with action_url and name", %{en_user: user} do
      url = "https://example.com/confirm/token"
      assert {:ok, _} = Mail.send_mail_verification(user, url)

      assert_email_sent(fn email ->
        assert email.subject =~ "Confirm your email"
        assert email.html_body =~ "Confirm your email"
        assert email.html_body =~ "Alice"
        assert email.html_body =~ url
        assert email.text_body =~ url
        refute_template_options(email)
      end)
    end

    test "renders DE body", %{de_user: user} do
      assert {:ok, _} = Mail.send_mail_verification(user, "https://example.com/confirm/token")

      assert_email_sent(fn email ->
        assert email.subject =~ "Bestätige deine E-Mail"
        assert email.html_body =~ "E-Mail bestätigen"
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_mail_verification_to/3
  # ---------------------------------------------------------------------------

  describe "send_mail_verification_to/3" do
    test "sends to override email but uses user's name and locale", %{de_user: user} do
      override_email = "new-email@example.com"
      url = "https://example.com/confirm/token"

      assert {:ok, _} = Mail.send_mail_verification_to(override_email, user, url)

      assert_email_sent(fn email ->
        assert [{"", "new-email@example.com"}] = email.to
        # German locale, user's name
        assert email.html_body =~ "E-Mail bestätigen"
        assert email.html_body =~ "Bob"
        assert email.html_body =~ url
        refute_template_options(email)
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_password_recovery/2
  # ---------------------------------------------------------------------------

  describe "send_password_recovery/2" do
    test "renders EN body with action_url and name", %{en_user: user} do
      url = "https://example.com/reset/token"
      assert {:ok, _} = Mail.send_password_recovery(user, url)

      assert_email_sent(fn email ->
        assert email.subject =~ "Reset your Magus password"
        assert email.html_body =~ "Reset your password"
        assert email.html_body =~ "Alice"
        assert email.html_body =~ url
        assert email.text_body =~ url
        refute_template_options(email)
      end)
    end

    test "renders DE body", %{de_user: user} do
      assert {:ok, _} = Mail.send_password_recovery(user, "https://example.com/reset/token")

      assert_email_sent(fn email ->
        assert email.subject =~ "Passwort zurück"
        assert email.html_body =~ "Passwort zurücksetzen"
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_welcome/1
  # ---------------------------------------------------------------------------

  describe "send_welcome/1" do
    test "renders EN body with magus_url CTA", %{en_user: user} do
      assert {:ok, _} = Mail.send_welcome(user)

      assert_email_sent(fn email ->
        assert email.subject =~ "Welcome to Magus"
        assert email.html_body =~ "Welcome to Magus"
        assert email.html_body =~ "Alice"
        # CTA links to product url
        assert email.html_body =~ "https://magus.digital"
        assert email.text_body =~ "https://magus.digital"
        refute_template_options(email)
      end)
    end

    test "renders DE body", %{de_user: user} do
      assert {:ok, _} = Mail.send_welcome(user)

      assert_email_sent(fn email ->
        assert email.subject =~ "Willkommen bei Magus"
        assert email.html_body =~ "Willkommen bei Magus"
        assert email.html_body =~ "Bob"
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_downgrade/1
  # ---------------------------------------------------------------------------

  describe "send_downgrade/1" do
    test "renders EN body", %{en_user: user} do
      assert {:ok, _} = Mail.send_downgrade(user)

      assert_email_sent(fn email ->
        assert email.subject != nil and email.subject != ""
        assert email.html_body =~ "Your plan has changed"
        assert email.html_body =~ "Alice"
        assert email.text_body != nil
        refute_template_options(email)
      end)
    end

    test "renders DE body", %{de_user: user} do
      assert {:ok, _} = Mail.send_downgrade(user)

      assert_email_sent(fn email ->
        assert email.html_body =~ "Dein Tarif hat sich geändert"
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_goodbye/1
  # ---------------------------------------------------------------------------

  describe "send_goodbye/1" do
    test "renders EN body", %{en_user: user} do
      assert {:ok, _} = Mail.send_goodbye(user)

      assert_email_sent(fn email ->
        assert email.subject != nil and email.subject != ""
        assert email.html_body =~ "Sorry to see you go"
        assert email.html_body =~ "Alice"
        refute_template_options(email)
      end)
    end

    test "renders DE body", %{de_user: user} do
      assert {:ok, _} = Mail.send_goodbye(user)

      assert_email_sent(fn email ->
        assert email.html_body =~ "Schade, dass du gehst"
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_upgraded/1
  # ---------------------------------------------------------------------------

  describe "send_upgraded/1" do
    test "renders EN body", %{en_user: user} do
      assert {:ok, _} = Mail.send_upgraded(user)

      assert_email_sent(fn email ->
        assert email.subject != nil and email.subject != ""
        assert email.html_body =~ "Thanks for upgrading"
        assert email.html_body =~ "Alice"
        refute_template_options(email)
      end)
    end

    test "renders DE body", %{de_user: user} do
      assert {:ok, _} = Mail.send_upgraded(user)

      assert_email_sent(fn email ->
        assert email.html_body =~ "Danke für dein Upgrade"
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # send_support_request/2
  # ---------------------------------------------------------------------------

  describe "send_support_request/2" do
    @form_data %{name: "Alice", email: "alice@example.com", topic: "bug", message: "Help!"}

    test "sends EN confirmation echoing topic and message", %{en_user: user} do
      assert {:ok, _} = Mail.send_support_request(user, @form_data)

      # Confirmation to the user
      assert_email_sent(fn email ->
        assert [{"", to_email}] = email.to
        assert to_email == to_string(user.email)
        assert email.subject =~ "received your support request"
        assert email.html_body =~ "We received your request"
        assert email.html_body =~ "Alice"
        # Echoes topic + message
        assert email.html_body =~ "bug"
        assert email.html_body =~ "Help!"
        assert email.text_body =~ "bug"
        assert email.text_body =~ "Help!"
        refute_template_options(email)
      end)
    end

    test "sends DE confirmation", %{de_user: user} do
      assert {:ok, _} = Mail.send_support_request(user, @form_data)

      assert_email_sent(fn email ->
        assert [{"", to_email}] = email.to
        assert to_email == to_string(user.email)
        assert email.html_body =~ "Wir haben deine Anfrage erhalten"
      end)
    end

    test "sends notification to support@magus.digital with reply_to", %{en_user: user} do
      assert {:ok, _} = Mail.send_support_request(user, @form_data)

      assert_receive {:email, %{to: [{"Magus Support", "support@magus.digital"}]} = email}
      assert email.subject == "Support Request [bug] from Alice"
      assert email.reply_to == {"Alice", "alice@example.com"}
      assert email.text_body =~ "Help!"
      assert email.text_body =~ "alice@example.com"
      assert email.text_body =~ "bug"
    end

    test "sends notification with plain email sender", _context do
      assert {:ok, _} = Mail.send_support_request("guest@example.com", @form_data)

      assert_receive {:email, %{to: [{"Magus Support", "support@magus.digital"}]} = email}
      assert email.reply_to == {"Alice", "alice@example.com"}
    end
  end

  # ---------------------------------------------------------------------------
  # Footer + language fallback
  # ---------------------------------------------------------------------------

  describe "footer and language fallback" do
    test "footer includes product name, year, support and discord links", %{en_user: user} do
      assert {:ok, _} = Mail.send_welcome(user)

      assert_email_sent(fn email ->
        assert email.html_body =~ "Magus"
        assert email.html_body =~ to_string(Date.utc_today().year)
        assert email.html_body =~ "https://magus.digital/help"
        assert email.html_body =~ "https://discord.gg/6EfPDhmWRb"

        assert email.text_body =~ to_string(Date.utc_today().year)
        assert email.text_body =~ "https://magus.digital/help"
        assert email.text_body =~ "https://discord.gg/6EfPDhmWRb"
      end)
    end

    test "defaults to EN when language is nil" do
      assert {:ok, _} =
               Mail.send_welcome(%{
                 email: "test@example.com",
                 display_name: "NoLang",
                 language: nil
               })

      assert_email_sent(fn email ->
        # EN copy, not German
        assert email.html_body =~ "Welcome to Magus"
        assert email.html_body =~ "NoLang"
      end)
    end
  end
end
