defmodule Magus.Agents.Context.DraftPrompts do
  @moduledoc """
  Predefined prompts for draft review and export operations.

  These prompts are used as trigger messages that instruct the conversation agent
  to perform specific draft-related tasks.
  """

  @doc """
  Returns a prompt instructing the agent to review the current draft.

  The agent should read the draft, check wording/clarity, verify links,
  flag hallucinated sources or dead links, check structure, and provide
  a review report in chat. It should NOT modify the draft.
  """
  def review_prompt do
    """
    Please review the current draft document. Use the read_draft tool to read its contents, then provide a thorough review covering:

    1. **Wording & Clarity** - Check for unclear phrasing, grammatical issues, and readability
    2. **Structure** - Evaluate the document's organization, flow, and logical structure
    3. **Links & Sources** - Verify any URLs or references. Flag any that appear broken, hallucinated, or unverifiable
    4. **Consistency** - Check for inconsistent terminology, formatting, or tone
    5. **Completeness** - Note any gaps, missing sections, or areas that need more detail

    Important: Do NOT modify the draft. Only provide your review as a response in this chat.
    This is a autogenerated message. Reply in the language of the user based on the context.
    """
  end

  @doc """
  Returns a prompt instructing the agent to export the draft in the given format.

  The agent should read the draft, load the appropriate skill, and use the
  coding sandbox to generate the file for download.
  """
  def export_prompt(:markdown, draft_id, draft_title) do
    """
    Please export the draft document "#{draft_title}" (ID: #{draft_id}) as a Markdown (.md) file. Follow these steps:

    1. Use the read_draft tool to get the draft content (draft ID: #{draft_id}). The content is already in Markdown format.
    2. Use sandbox_write_file to save the raw Markdown content (without the line numbers added by read_draft) to a `.md` file in `/workspace/`.
    3. Use sandbox_download_file to make the file available for download, then include the download link in your reply.

    Do not run code or transform the content; just write the Markdown verbatim.
    This is a autogenerated message. Reply in the language of the user based on the context.
    """
  end

  def export_prompt(format, draft_id, draft_title) do
    {format_name, skill_name} = format_config(format)

    """
    Please export the draft document "#{draft_title}" (ID: #{draft_id}) as a #{format_name} file. Follow these steps:

    1. Use the read_draft tool to get the draft content (draft ID: #{draft_id})
    2. Load the "#{skill_name}" skill for formatting guidance
    3. Use the run_code tool to generate the #{format_name} file from the draft content
    4. Make the generated file available for download

    The output should be a well-formatted #{format_name} document that preserves the draft's structure, headings, and formatting.
    This is a autogenerated message. Reply in the language of the user based on the context.
    """
  end

  defp format_config(:pdf), do: {"PDF", "pdf_documents"}
  defp format_config(:docx), do: {"Word (DOCX)", "word_documents"}
  defp format_config(:latex), do: {"LaTeX", "latex_documents"}
end
