defmodule Magus.Brain.PageVersionPolicyTest do
  @moduledoc """
  Verifies the security fix wired in Phase A: `Magus.Brain.Page.Version` is
  generated by AshPaperTrail with `Ash.Policy.Authorizer` attached and no
  policies defined, so all user-facing reads are forbidden by default and
  only internal callers (using `authorize?: false`) can read version rows.

  Without this guard, any caller with the module name (`Magus.Brain.Page.Version`)
  could `Ash.read` the resource and leak page titles, slugs, parent ids, etc.
  """

  use Magus.DataCase, async: true

  import Magus.Generators

  alias Magus.Brain

  describe "Magus.Brain.Page.Version" do
    test "forbids reads by a user actor" do
      user = generate(user())
      {:ok, brain} = Brain.create_brain(%{title: "Test"}, actor: user)
      {:ok, page} = Brain.create_page(brain.id, %{title: "Original"}, actor: user)

      # Mutate to ensure at least one version row exists.
      {:ok, _renamed} = Brain.update_page_title(page, %{title: "Renamed"}, actor: user)

      require Ash.Query

      assert {:error, %Ash.Error.Forbidden{}} =
               Magus.Brain.Page.Version
               |> Ash.Query.filter(version_source_id == ^page.id)
               |> Ash.read(actor: user)
    end

    test "allows reads with authorize?: false (internal pipeline path)" do
      user = generate(user())
      {:ok, brain} = Brain.create_brain(%{title: "Test"}, actor: user)
      {:ok, page} = Brain.create_page(brain.id, %{title: "Original"}, actor: user)
      {:ok, _renamed} = Brain.update_page_title(page, %{title: "Renamed"}, actor: user)

      require Ash.Query

      assert {:ok, versions} =
               Magus.Brain.Page.Version
               |> Ash.Query.filter(version_source_id == ^page.id)
               |> Ash.read(authorize?: false)

      assert length(versions) >= 1
    end
  end
end
