defmodule Magus.ResourceCase do
  @moduledoc """
  This module defines the test case for Ash resource tests.

  It provides helpers for:
  - Database sandbox setup
  - Test data generation via Magus.Generators
  - Authorization testing helpers
  - Mox integration for mocking

  ## Usage

      defmodule Magus.Chat.ConversationTest do
        use Magus.ResourceCase, async: true

        describe "create conversation" do
          test "creates with valid attributes" do
            user = generate(user())
            {:ok, conversation} = Chat.create_conversation(%{title: "Test"}, actor: user)
            assert conversation.title == "Test"
          end
        end
      end
  """

  use ExUnit.CaseTemplate

  using do
    quote do
      import Magus.Generators
      import Magus.ResourceCase
      import Mox

      alias Magus.Accounts
      alias Magus.Chat
      alias Magus.Library

      # Setup Mox for async tests
      setup :verify_on_exit!
    end
  end

  setup tags do
    Magus.DataCase.setup_sandbox(tags)
    stub_batch_embedder()
    :ok
  end

  # Default Mox stub for the Super Brain extraction batch embedder.
  #
  # The Super Brain extraction pipeline calls
  # `Magus.Embeddings.BatchEmbedderMock` for every Episode raw_text and
  # entity-name batch. Returning zero-vectors of the configured embedding
  # dimension means existing worker tests do not have to set explicit
  # expectations: they get a deterministic shape that exercises the full
  # graph-write path. Tests that care about embedding contents override
  # this via their own `expect/3` (which takes precedence in Mox).
  defp stub_batch_embedder do
    dim = 1536
    zero_vec = List.duplicate(0.0, dim)

    Mox.stub(Magus.Embeddings.BatchEmbedderMock, :embed_many, fn texts ->
      {:ok, Enum.map(texts, fn _ -> zero_vec end)}
    end)

    Mox.stub(Magus.Embeddings.BatchEmbedderMock, :embed_one, fn _text ->
      {:ok, zero_vec}
    end)

    :ok
  rescue
    # Mox raises if the mock isn't loaded yet (e.g. when ResourceCase is
    # used outside the standard test boot). Ignore so non-extraction
    # tests still work.
    _ -> :ok
  end

  # ---------------------------------------------------------------------------
  # Test Helpers
  # ---------------------------------------------------------------------------

  @doc """
  Creates a user and returns it for use as an actor in tests.

  ## Examples

      test "user can create conversation" do
        actor = create_actor()
        {:ok, conv} = Chat.create_conversation(%{title: "Test"}, actor: actor)
        assert conv.user_id == actor.id
      end
  """
  def create_actor(opts \\ []) do
    import Magus.Generators
    generate(user(opts))
  end

  @doc """
  Asserts that an actor is authorized to perform an action.

  Uses the domain's `can_action_name?/2` function generated by Ash.

  ## Examples

      assert_authorized(Chat, :rename_conversation, user, conversation)
  """
  defmacro assert_authorized(domain, action, actor, record \\ nil) do
    quote do
      can_func = :"can_#{unquote(action)}?"

      result =
        if unquote(record) do
          apply(unquote(domain), can_func, [unquote(actor), unquote(record)])
        else
          apply(unquote(domain), can_func, [unquote(actor)])
        end

      assert result, "Expected #{unquote(actor)} to be authorized for #{unquote(action)}"
    end
  end

  @doc """
  Refutes that an actor is authorized to perform an action.

  ## Examples

      refute_authorized(Chat, :rename_conversation, other_user, conversation)
  """
  defmacro refute_authorized(domain, action, actor, record \\ nil) do
    quote do
      can_func = :"can_#{unquote(action)}?"

      result =
        if unquote(record) do
          apply(unquote(domain), can_func, [unquote(actor), unquote(record)])
        else
          apply(unquote(domain), can_func, [unquote(actor)])
        end

      refute result, "Expected #{unquote(actor)} to NOT be authorized for #{unquote(action)}"
    end
  end

  @doc """
  Asserts that an Ash error contains a specific field error.

  ## Examples

      {:error, error} = Chat.create_message(%{}, actor: user)
      assert_field_error(error, :text, "is required")
  """
  def assert_field_error(%Ash.Error.Invalid{} = error, field, message_substring) do
    field_errors =
      error.errors
      |> Enum.filter(fn e ->
        Map.get(e, :field) == field or field in (Map.get(e, :fields) || [])
      end)

    assert length(field_errors) > 0,
           "Expected error on field #{inspect(field)}, got: #{inspect(error.errors)}"

    matching =
      Enum.any?(field_errors, fn e ->
        msg = Map.get(e, :message, "")
        String.contains?(to_string(msg), message_substring)
      end)

    assert matching,
           "Expected error message containing #{inspect(message_substring)} on field #{inspect(field)}"
  end

  def assert_field_error(error, field, message_substring) do
    # Handle wrapped errors
    case error do
      %{errors: errors} when is_list(errors) ->
        assert_field_error(%Ash.Error.Invalid{errors: errors}, field, message_substring)

      _ ->
        flunk("Expected Ash.Error.Invalid, got: #{inspect(error)}")
    end
  end

  @doc """
  Asserts that an action returns a forbidden error.

  ## Examples

      assert_forbidden(fn ->
        Chat.delete_conversation(conversation, actor: other_user)
      end)
  """
  def assert_forbidden(fun) when is_function(fun, 0) do
    case fun.() do
      {:error, %Ash.Error.Forbidden{}} ->
        :ok

      {:error, error} ->
        # Check if it's wrapped
        if forbidden_error?(error) do
          :ok
        else
          flunk("Expected Forbidden error, got: #{inspect(error)}")
        end

      {:ok, result} ->
        flunk("Expected Forbidden error, got success: #{inspect(result)}")
    end
  end

  defp forbidden_error?(%{class: :forbidden}), do: true

  defp forbidden_error?(%{errors: errors}) when is_list(errors),
    do: Enum.any?(errors, &forbidden_error?/1)

  defp forbidden_error?(_), do: false

  @doc """
  Waits for an Oban job to be enqueued.

  Useful for testing actions that trigger background jobs.

  ## Examples

      message = generate(message(actor: user, conversation_id: conv.id))
      assert_oban_job_enqueued(worker: Magus.Chat.Message.Workers.Respond)
  """
  defmacro assert_oban_job_enqueued(opts) do
    quote do
      use Oban.Testing, repo: Magus.Repo
      assert_enqueued(unquote(opts))
    end
  end
end
