import Config

config :ash, policies: [show_policy_breakdowns?: true]

# Lets local/Bypass MCP servers on 127.0.0.1 pass SSRF validation in dev.
config :magus, Magus.MCP, allow_private_urls: true

# Configure your database
config :magus, Magus.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "omnios_dev",
  stacktrace: true,
  log: false,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :magus, MagusWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LPi6rFZ3VK+twtvs2RTws6N1ydAgV99GIRbF8Fr6pDTycPqA9t4qme/98g4hYDVm",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:magus, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:magus, ~w(--watch)]},
    # SvelteKit SPA dev server with hot-reload. Starts/stops with `mix phx.server`
    # and serves the SPA at http://localhost:5173/next (the exact port is printed
    # in this console if 5173 is taken), proxying /rpc, /uploads, /socket, etc.
    # back to this Phoenix server (see frontend/vite.config.ts). Use this URL in
    # dev for instant updates; `priv/static/next` (npm run build) is only for prod.
    # The static adapter's `vite build --watch` is unreliable (its prerender/
    # fallback step crashes on rebuild), so dev uses the HMR server instead.
    npm: ["run", "dev", cd: Path.expand("../frontend", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :magus, MagusWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/magus_web/router\.ex$"E,
      ~r"lib/magus_web/.*/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox.
# Dev-only token signing secret. Production signs tokens with a secret loaded
# from the environment (see config/runtime.exs); generate your own dev value
# with `mix phx.gen.secret` if you prefer.
config :magus, dev_routes: true, token_signing_secret: "dev-only-token-signing-secret-replace-me"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Use local file storage in development
config :magus, :storage_backend, :local

config :magus, Magus.Graph,
  host: "127.0.0.1",
  port: 6380,
  pool_size: 10

# Allow running a second dev server (e.g. from a worktree) without the
# LiveDebugger endpoint colliding on its fixed port.
if System.get_env("DISABLE_LIVE_DEBUGGER") == "1" do
  config :live_debugger, disabled?: true
end
