defmodule Magus.Repo.Migrations.AddDisabledToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :disabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:messages) do
      remove :disabled
    end
  end
end
