defmodule Magus.Repo.Migrations.AddSupportsToolsToModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :supports_tools?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:models) do
      remove :supports_tools?
    end
  end
end
