defmodule Magus.Repo.Migrations.AddInfoToModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :info, :text
    end
  end

  def down do
    alter table(:models) do
      remove :info
    end
  end
end
