defmodule Magus.Repo.Migrations.AddModelAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :default?, :boolean, null: false, default: false
      add :context_window, :bigint
      add :input_cost, :text
      add :output_cost, :text
    end
  end

  def down do
    alter table(:models) do
      remove :output_cost
      remove :input_cost
      remove :context_window
      remove :default?
    end
  end
end
