defmodule Magus.Repo.Migrations.AddDefaultImageModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :selected_image_model_id,
          references(:models,
            column: :id,
            name: "users_selected_image_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:models) do
      add :default_image?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:models) do
      remove :default_image?
    end

    drop constraint(:users, "users_selected_image_model_id_fkey")

    alter table(:users) do
      remove :selected_image_model_id
    end
  end
end
