defmodule Magus.Repo.Migrations.AddUserSettingsFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :language, :text, null: false, default: "en"
      add :avatar_path, :text
      add :pending_email, :citext
    end
  end

  def down do
    alter table(:users) do
      remove :pending_email
      remove :avatar_path
      remove :language
    end
  end
end
