defmodule Magus.Repo.Migrations.AddApiProviderToModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :api_provider, :text, null: false, default: "openrouter"
    end
  end

  def down do
    alter table(:models) do
      remove :api_provider
    end
  end
end
