defmodule Magus.Repo.Migrations.AddBrainUserRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stacks_blocks) do
      modify :position, :bigint, default: 0
    end

    create unique_index(:stacks_blocks, [:stack_id, :block_id],
             name: "stacks_blocks_unique_block_in_stack_index"
           )

    alter table(:stacks) do
      add :user_id,
          references(:users,
            column: :id,
            name: "stacks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:blocks) do
      modify :variables, :map, default: %{}
      modify :metadata, :map, default: %{}

      add :user_id,
          references(:users,
            column: :id,
            name: "blocks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:blocks, "blocks_user_id_fkey")

    alter table(:blocks) do
      remove :user_id
      modify :metadata, :map, default: nil
      modify :variables, :map, default: nil
    end

    drop constraint(:stacks, "stacks_user_id_fkey")

    alter table(:stacks) do
      remove :user_id
    end

    drop_if_exists unique_index(:stacks_blocks, [:stack_id, :block_id],
                     name: "stacks_blocks_unique_block_in_stack_index"
                   )

    alter table(:stacks_blocks) do
      modify :position, :bigint, default: nil
    end
  end
end
