defmodule Magus.Repo.Migrations.AddModelDescriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :short_description, :text
      add :detailed_description, :text
      add :released_at, :date
    end
  end

  def down do
    alter table(:models) do
      remove :released_at
      remove :detailed_description
      remove :short_description
    end
  end
end
