defmodule Magus.Repo.Migrations.AddContextRefactor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversation_contexts) do
      add :needs_checkpoint, :boolean, null: false, default: false
      add :pending_checkpoint_message_id, :uuid
    end
  end

  def down do
    alter table(:conversation_contexts) do
      remove :pending_checkpoint_message_id
      remove :needs_checkpoint
    end
  end
end
