defmodule Magus.Repo.Migrations.AddReasoningDetailsToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :reasoning_details, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:messages) do
      remove :reasoning_details
    end
  end
end
