defmodule Magus.Repo.Migrations.AddModelIdAndVideoDurationToMessageUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message_usages) do
      add :video_duration, :decimal

      add :model_id,
          references(:models,
            column: :id,
            name: "message_usages_model_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:message_usages, "message_usages_model_id_fkey")

    alter table(:message_usages) do
      remove :model_id
      remove :video_duration
    end
  end
end
