defmodule Magus.Repo.Migrations.AddSelectedModelToMessage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :selected_model_id,
          references(:models,
            column: :id,
            name: "messages_selected_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:messages, "messages_selected_model_id_fkey")

    alter table(:messages) do
      remove :selected_model_id
    end
  end
end
