defmodule Magus.Repo.Migrations.AddSourceToResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Drop and recreate column - old format (jsonb[]) incompatible with new (uuid[])
    alter table(:messages) do
      remove :attachments
    end

    alter table(:messages) do
      add :attachments, {:array, :uuid}, null: false, default: []
    end

    alter table(:memory_resources) do
      add :source, :text, null: false, default: "user"
    end
  end

  def down do
    alter table(:memory_resources) do
      remove :source
    end

    alter table(:messages) do
      remove :attachments
    end

    alter table(:messages) do
      add :attachments, {:array, :map}, null: false, default: []
    end
  end
end
