defmodule Magus.Repo.Migrations.AddModelsV2Features do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :input_modalities, {:array, :text}, null: false, default: ["text"]
      add :output_modalities, {:array, :text}, null: false, default: ["text"]
      add :supports_search?, :boolean, null: false, default: false
      add :supports_reasoning?, :boolean, null: false, default: false
    end

    alter table(:messages) do
      add :mode, :text, null: false, default: "chat"
      add :model_name, :text
      add :citations, {:array, :map}, null: false, default: []
      add :reasoning_summary, {:array, :text}, null: false, default: []
    end

    alter table(:conversations) do
      add :chat_mode, :text, null: false, default: "chat"
    end
  end

  def down do
    alter table(:conversations) do
      remove :chat_mode
    end

    alter table(:messages) do
      remove :reasoning_summary
      remove :citations
      remove :model_name
      remove :mode
    end

    alter table(:models) do
      remove :supports_reasoning?
      remove :supports_search?
      remove :output_modalities
      remove :input_modalities
    end
  end
end
