defmodule Magus.Repo.Migrations.AddMessageTypeToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :message_type, :text, null: false, default: "message"
    end
  end

  def down do
    alter table(:messages) do
      remove :message_type
    end
  end
end
