defmodule Magus.Repo.Migrations.CreateMessageUsages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:message_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :model, :text, null: false
      add :usage_type, :text, default: "response"
      add :prompt_tokens, :bigint, default: 0
      add :completion_tokens, :bigint, default: 0
      add :total_tokens, :bigint, default: 0
      add :reasoning_tokens, :bigint
      add :audio_tokens, :bigint
      add :accepted_prediction_tokens, :bigint
      add :rejected_prediction_tokens, :bigint
      add :cached_tokens, :bigint, default: 0
      add :cache_write_tokens, :bigint, default: 0
      add :prompt_audio_tokens, :bigint
      add :video_tokens, :bigint
      add :input_cost, :decimal, default: "0"
      add :output_cost, :decimal, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "message_usages_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          ),
          null: false

      add :message_id,
          references(:messages,
            column: :id,
            name: "message_usages_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "message_usages_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:message_usages, "message_usages_user_id_fkey")

    drop constraint(:message_usages, "message_usages_message_id_fkey")

    drop constraint(:message_usages, "message_usages_conversation_id_fkey")

    drop table(:message_usages)
  end
end
