defmodule Magus.Repo.Migrations.AddUiPreferencesToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :ui_preferences, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:users) do
      remove :ui_preferences
    end
  end
end
