defmodule Magus.Repo.Migrations.AddMemoryResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memory_resources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false
      add :mime_type, :text, null: false
      add :file_size, :bigint, null: false
      add :file_path, :text, null: false
      add :storage_backend, :text, null: false, default: "local"
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :metadata, :map, default: %{}
      add :chunk_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memory_resources_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "memory_resources_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :folder_id,
          references(:folders,
            column: :id,
            name: "memory_resources_folder_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:memory_chunks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :content, :text, null: false
      add :position, :bigint, null: false
      add :token_count, :bigint, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :resource_id,
          references(:memory_resources,
            column: :id,
            name: "memory_chunks_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    # Add vector column using pgvector extension (3072 dimensions for text-embedding-3-large)
    execute "ALTER TABLE memory_chunks ADD COLUMN embedding vector(1536)"

    # Create HNSW index for efficient similarity search
    execute """
    CREATE INDEX memory_chunks_embedding_idx ON memory_chunks
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64)
    """

    # Create indexes for common queries
    create index(:memory_resources, [:user_id])
    create index(:memory_resources, [:conversation_id])
    create index(:memory_resources, [:folder_id])
    create index(:memory_resources, [:status])
    create index(:memory_chunks, [:resource_id])
  end

  def down do
    drop_if_exists index(:memory_chunks, [:resource_id])
    drop_if_exists index(:memory_resources, [:status])
    drop_if_exists index(:memory_resources, [:folder_id])
    drop_if_exists index(:memory_resources, [:conversation_id])
    drop_if_exists index(:memory_resources, [:user_id])

    execute "DROP INDEX IF EXISTS memory_chunks_embedding_idx"

    drop constraint(:memory_chunks, "memory_chunks_resource_id_fkey")
    drop table(:memory_chunks)

    drop constraint(:memory_resources, "memory_resources_user_id_fkey")
    drop constraint(:memory_resources, "memory_resources_conversation_id_fkey")
    drop constraint(:memory_resources, "memory_resources_folder_id_fkey")
    drop table(:memory_resources)
  end
end
