defmodule Magus.Repo.Migrations.Base do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :settings, :map, null: false, default: %{}
      add :total_tokens_used, :bigint, null: false, default: 0
      add :token_limit, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "workspaces_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:workspace_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :invited_at, :utc_datetime_usec
      add :accepted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_members_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "workspace_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "workspace_members_invited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:workspace_members, [:workspace_id, :user_id],
             name: "workspace_members_unique_membership_index"
           )

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :total_tokens_used, :bigint, null: false, default: 0
      add :total_input_tokens, :bigint, null: false, default: 0
      add :total_output_tokens, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "sessions_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "sessions_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :model_id, :uuid, null: false
    end

    create table(:models, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sessions) do
      modify :model_id,
             references(:models,
               column: :id,
               name: "sessions_model_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:models) do
      add :name, :text, null: false
      add :key, :text, null: false
      add :settings, :map, null: false, default: %{}
      add :active?, :boolean, null: false, default: true
      add :provider, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :model, :text
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :attachments, {:array, :map}, null: false, default: []
      add :metadata, :map, null: false, default: %{}
      add :status, :text, null: false, default: "complete"
      add :error, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :text, :text, null: false
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true

      add :session_id,
          references(:sessions,
            column: :id,
            name: "messages_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "messages_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :conversation_id, :uuid, null: false
      add :response_to_id, :uuid
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :response_to_id,
             references(:messages,
               column: :id,
               name: "messages_response_to_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "conversations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:conversations, "conversations_user_id_fkey")

    alter table(:conversations) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_response_to_id_fkey")

    alter table(:messages) do
      modify :response_to_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop constraint(:messages, "messages_session_id_fkey")

    drop constraint(:messages, "messages_created_by_id_fkey")

    drop table(:messages)

    alter table(:models) do
      remove :updated_at
      remove :inserted_at
      remove :provider
      remove :active?
      remove :settings
      remove :key
      remove :name
    end

    drop constraint(:sessions, "sessions_model_id_fkey")

    alter table(:sessions) do
      modify :model_id, :uuid
    end

    drop table(:models)

    drop constraint(:sessions, "sessions_created_by_id_fkey")

    drop constraint(:sessions, "sessions_workspace_id_fkey")

    drop table(:sessions)

    drop_if_exists unique_index(:workspace_members, [:workspace_id, :user_id],
                     name: "workspace_members_unique_membership_index"
                   )

    drop constraint(:workspace_members, "workspace_members_workspace_id_fkey")

    drop constraint(:workspace_members, "workspace_members_user_id_fkey")

    drop constraint(:workspace_members, "workspace_members_invited_by_id_fkey")

    drop table(:workspace_members)

    drop constraint(:workspaces, "workspaces_owner_id_fkey")

    drop table(:workspaces)
  end
end
