defmodule Magus.Repo.Migrations.AddUserFolderStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_folder_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :is_expanded, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_folder_states_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :folder_id,
          references(:folders,
            column: :id,
            name: "user_folder_states_folder_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:user_folder_states, [:user_id, :folder_id],
             name: "user_folder_states_unique_user_folder_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_folder_states, [:user_id, :folder_id],
                     name: "user_folder_states_unique_user_folder_index"
                   )

    drop constraint(:user_folder_states, "user_folder_states_user_id_fkey")

    drop constraint(:user_folder_states, "user_folder_states_folder_id_fkey")

    drop table(:user_folder_states)
  end
end
