defmodule Magus.Repo.Migrations.SimplifyConversationContext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversation_contexts) do
      remove :output_cost
      remove :input_cost
      remove :output_tokens_total
      remove :input_tokens_total
    end
  end

  def down do
    alter table(:conversation_contexts) do
      add :input_tokens_total, :bigint, null: false, default: 0
      add :output_tokens_total, :bigint, null: false, default: 0
      add :input_cost, :decimal, null: false, default: "0"
      add :output_cost, :decimal, null: false, default: "0"
    end
  end
end
