defmodule Magus.Repo.Migrations.What do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memory_chunks) do
      modify :embedding, :vector
    end
  end

  def down do
    alter table(:memory_chunks) do
      modify :embedding, {:array, :float}
    end
  end
end
