defmodule Magus.Repo.Migrations.AddConversationContexts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversation_contexts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :context_tokens_used, :bigint, null: false, default: 0
      add :input_tokens_total, :bigint, null: false, default: 0
      add :output_tokens_total, :bigint, null: false, default: 0
      add :input_cost, :decimal, null: false, default: "0"
      add :output_cost, :decimal, null: false, default: "0"
      add :summary, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_contexts_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :model_id,
          references(:models,
            column: :id,
            name: "conversation_contexts_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :checkpoint_message_id,
          references(:messages,
            column: :id,
            name: "conversation_contexts_checkpoint_message_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversation_contexts, "conversation_contexts_conversation_id_fkey")

    drop constraint(:conversation_contexts, "conversation_contexts_model_id_fkey")

    drop constraint(:conversation_contexts, "conversation_contexts_checkpoint_message_id_fkey")

    drop table(:conversation_contexts)
  end
end
