defmodule Magus.Repo.Migrations.AddBrainDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stacks_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :stack_id, :uuid, null: false
      add :block_id, :uuid, null: false
    end

    create table(:stacks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:stacks_blocks) do
      modify :stack_id,
             references(:stacks,
               column: :id,
               name: "stacks_blocks_stack_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:stacks) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:stacks_blocks) do
      modify :block_id,
             references(:blocks,
               column: :id,
               name: "stacks_blocks_block_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:blocks) do
      add :name, :text, null: false
      add :content, :text, null: false
      add :type, :text, null: false
      add :metadata, :map
      add :variables, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:blocks) do
      remove :updated_at
      remove :inserted_at
      remove :variables
      remove :metadata
      remove :type
      remove :content
      remove :name
    end

    drop constraint(:stacks_blocks, "stacks_blocks_block_id_fkey")

    alter table(:stacks_blocks) do
      modify :block_id, :uuid
    end

    drop table(:blocks)

    alter table(:stacks) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:stacks_blocks, "stacks_blocks_stack_id_fkey")

    alter table(:stacks_blocks) do
      modify :stack_id, :uuid
    end

    drop table(:stacks)

    drop table(:stacks_blocks)
  end
end
