defmodule Magus.Repo.Migrations.AddFoldersAndTabs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:open_tabs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, default: 0
      add :opened_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "open_tabs_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "open_tabs_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:open_tabs, [:user_id, :conversation_id],
             name: "open_tabs_unique_user_conversation_index"
           )

    create table(:folders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :position, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "folders_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :parent_id,
          references(:folders,
            column: :id,
            name: "folders_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:conversations) do
      add :folder_id,
          references(:folders,
            column: :id,
            name: "conversations_folder_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_folder_id_fkey")

    alter table(:conversations) do
      remove :folder_id
    end

    drop constraint(:folders, "folders_user_id_fkey")

    drop constraint(:folders, "folders_parent_id_fkey")

    drop table(:folders)

    drop_if_exists unique_index(:open_tabs, [:user_id, :conversation_id],
                     name: "open_tabs_unique_user_conversation_index"
                   )

    drop constraint(:open_tabs, "open_tabs_user_id_fkey")

    drop constraint(:open_tabs, "open_tabs_conversation_id_fkey")

    drop table(:open_tabs)
  end
end
