defmodule Magus.Repo.Migrations.AddWorkspaceFilesToSandbox do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sandboxes) do
      add :workspace_files, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:sandboxes) do
      remove :workspace_files
    end
  end
end
