defmodule Magus.Repo.Migrations.AddPaneStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pane_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :pane_type, :text
      add :resource_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "pane_states_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "pane_states_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:pane_states, [:conversation_id, :user_id],
             name: "pane_states_unique_conversation_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:pane_states, [:conversation_id, :user_id],
                     name: "pane_states_unique_conversation_user_index"
                   )

    drop constraint(:pane_states, "pane_states_conversation_id_fkey")

    drop constraint(:pane_states, "pane_states_user_id_fkey")

    drop table(:pane_states)
  end
end
