defmodule Magus.Repo.Migrations.AddWorkspaceStorageUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :storage_usage_bytes, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:workspaces) do
      remove :storage_usage_bytes
    end
  end
end
