defmodule Magus.Repo.Migrations.UpdateUniqueInviteIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:workspace_members, [:workspace_id, :invite_email],
                     name: "workspace_members_unique_invite_index"
                   )

    create unique_index(:workspace_members, [:workspace_id, :invite_email],
             name: "workspace_members_unique_invite_index",
             where: "(status != 'deactivated')"
           )
  end

  def down do
    drop_if_exists unique_index(:workspace_members, [:workspace_id, :invite_email],
                     name: "workspace_members_unique_invite_index"
                   )

    create unique_index(:workspace_members, [:workspace_id, :invite_email],
             name: "workspace_members_unique_invite_index"
           )
  end
end
