defmodule Magus.Repo.Migrations.AddOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :billing_interval, :text, null: false, default: "monthly"
      add :billing_status, :text, null: false, default: "active"
      add :stripe_customer_id, :text
      add :stripe_subscription_id, :text
      add :stripe_subscription_item_id, :text
      add :current_period_start, :utc_datetime_usec
      add :current_period_end, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "organizations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:organizations_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false

      add :version_source_id,
          references(:organizations,
            column: :id,
            name: "organizations_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "organizations_versions_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:organizations_versions, "organizations_versions_version_source_id_fkey")

    drop constraint(:organizations_versions, "organizations_versions_owner_id_fkey")

    drop table(:organizations_versions)

    drop constraint(:organizations, "organizations_owner_id_fkey")

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop table(:organizations)
  end
end
