defmodule Magus.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:seat_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :sponsor_user_id,
          references(:users,
            column: :id,
            name: "seat_grants_sponsor_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recipient_email, :citext, null: false

      add :recipient_user_id,
          references(:users,
            column: :id,
            name: "seat_grants_recipient_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :usage_plan_id,
          references(:usage_plans,
            column: :id,
            name: "seat_grants_usage_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :status, :text, null: false, default: "invited"
      add :invite_token, :text, null: false
      add :invite_expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:seat_grants, [:sponsor_user_id, :recipient_email],
             name: "seat_grants_unique_active_grant_index",
             where: "(status != 'revoked')"
           )

    create unique_index(:seat_grants, [:invite_token], name: "seat_grants_unique_token_index")
  end

  def down do
    drop_if_exists unique_index(:seat_grants, [:invite_token],
                     name: "seat_grants_unique_token_index"
                   )

    drop_if_exists unique_index(:seat_grants, [:sponsor_user_id, :recipient_email],
                     name: "seat_grants_unique_active_grant_index"
                   )

    drop constraint(:seat_grants, "seat_grants_sponsor_user_id_fkey")

    drop constraint(:seat_grants, "seat_grants_recipient_user_id_fkey")

    drop constraint(:seat_grants, "seat_grants_usage_plan_id_fkey")

    drop table(:seat_grants)
  end
end
