defmodule Magus.Repo.Migrations.AddModeFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_plans) do
      add :image_generation_enabled, :boolean, null: false, default: false
      add :video_generation_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:usage_plans) do
      remove :video_generation_enabled
      remove :image_generation_enabled
    end
  end
end
