defmodule Magus.Repo.Migrations.AddBrainConnectionsAndAccesses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:brain_accesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :grantee_type, :text, null: false
      add :grantee_id, :uuid, null: false
      add :role, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brain_id,
          references(:brains,
            column: :id,
            name: "brain_accesses_brain_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:brain_accesses, [:brain_id, :grantee_type, :grantee_id],
             name: "brain_accesses_unique_grantee_per_brain_index"
           )

    create table(:brain_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :type, :text, null: false
      add :weight, :float, default: 0.5
      add :is_explicit, :boolean, default: false
      add :contributor_type, :text
      add :contributor_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_block_id,
          references(:brain_blocks,
            column: :id,
            name: "brain_connections_source_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :target_block_id,
          references(:brain_blocks,
            column: :id,
            name: "brain_connections_target_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :target_page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_connections_target_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:brain_connections, "brain_connections_source_block_id_fkey")

    drop constraint(:brain_connections, "brain_connections_target_block_id_fkey")

    drop constraint(:brain_connections, "brain_connections_target_page_id_fkey")

    drop table(:brain_connections)

    drop_if_exists unique_index(:brain_accesses, [:brain_id, :grantee_type, :grantee_id],
                     name: "brain_accesses_unique_grantee_per_brain_index"
                   )

    drop constraint(:brain_accesses, "brain_accesses_brain_id_fkey")

    drop table(:brain_accesses)
  end
end
