defmodule Magus.Repo.Migrations.AddIsTemplateToFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :is_template, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:files) do
      remove :is_template
    end
  end
end
