defmodule Magus.Repo.Migrations.ReplaceAutoRechargeWithNoSpendCap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_subscriptions) do
      remove :auto_recharge_threshold_cents
      remove :auto_recharge_amount_cents
      remove :auto_recharge_enabled
      add :no_spend_cap, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:user_subscriptions) do
      remove :no_spend_cap
      add :auto_recharge_enabled, :boolean, null: false, default: false
      add :auto_recharge_amount_cents, :bigint
      add :auto_recharge_threshold_cents, :bigint
    end
  end
end
