defmodule Magus.Repo.Migrations.AddConnectorFieldsToFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :external_id, :text
      add :external_etag, :text
      add :external_updated_at, :utc_datetime_usec
      add :external_url, :text
      add :last_synced_at, :utc_datetime_usec
      add :deleted_at, :utc_datetime_usec

      add :knowledge_collection_id,
          references(:knowledge_collections,
            column: :id,
            name: "files_knowledge_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:files, [:knowledge_collection_id, :external_id],
             name: "files_unique_collection_external_index",
             where: "(knowledge_collection_id IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:files, [:knowledge_collection_id, :external_id],
                     name: "files_unique_collection_external_index"
                   )

    drop constraint(:files, "files_knowledge_collection_id_fkey")

    alter table(:files) do
      remove :knowledge_collection_id
      remove :deleted_at
      remove :last_synced_at
      remove :external_url
      remove :external_updated_at
      remove :external_etag
      remove :external_id
    end
  end
end
