defmodule Magus.Repo.Migrations.AddWorkspaceCreationEnabledToPlans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_plans) do
      add :workspace_creation_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:usage_plans) do
      remove :workspace_creation_enabled
    end
  end
end
