defmodule Magus.Repo.Migrations.AddConversationModeModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :selected_image_model_id,
          references(:models,
            column: :id,
            name: "conversations_selected_image_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :selected_video_model_id,
          references(:models,
            column: :id,
            name: "conversations_selected_video_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_selected_image_model_id_fkey")

    drop constraint(:conversations, "conversations_selected_video_model_id_fkey")

    alter table(:conversations) do
      remove :selected_video_model_id
      remove :selected_image_model_id
    end
  end
end
