defmodule Magus.Repo.Migrations.AddActionNameToMessageUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message_usages) do
      add :action_name, :text
    end
  end

  def down do
    alter table(:message_usages) do
      remove :action_name
    end
  end
end
