defmodule Magus.Repo.Migrations.AddPlanDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      add :delivered_at, :utc_datetime_usec
      add :delivery_ref, :text
    end
  end

  def down do
    alter table(:brain_pages) do
      remove :delivery_ref
      remove :delivered_at
    end
  end
end
