defmodule Magus.Repo.Migrations.TabSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tab_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mode, :text, null: false, default: "chat"
      add :nav_filter, :text, null: false, default: "all"
      add :tabs, {:array, :map}, null: false, default: []
      add :active_tab_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "tab_sessions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "tab_sessions_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:tab_sessions, [:user_id, :workspace_id],
             name: :tab_sessions_user_workspace_unique,
             nulls_distinct: false
           )

    create index(:tab_sessions, [:workspace_id])
  end

  def down do
    drop index(:tab_sessions, [:workspace_id])

    drop index(:tab_sessions, [:user_id, :workspace_id],
           name: :tab_sessions_user_workspace_unique
         )

    drop constraint(:tab_sessions, "tab_sessions_user_id_fkey")

    drop constraint(:tab_sessions, "tab_sessions_workspace_id_fkey")

    drop table(:tab_sessions)
  end
end
