defmodule Magus.Repo.Migrations.AddTriageModelToCustomAgents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :triage_model_id,
          references(:models,
            column: :id,
            name: "custom_agents_triage_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:custom_agents, "custom_agents_triage_model_id_fkey")

    alter table(:custom_agents) do
      remove :triage_model_id
    end
  end
end
