defmodule Magus.Repo.Migrations.CreatePlanDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:plan_task_pane_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :pane_open, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "plan_task_pane_states_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "plan_task_pane_states_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:plan_task_pane_states, [:conversation_id, :user_id],
             name: "plan_task_pane_states_unique_conversation_user_index"
           )

    create table(:plan_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "open"
      add :position, :bigint
      add :assigned_to_agent, :text
      add :completed_by, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "plan_tasks_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :parent_id,
          references(:plan_tasks,
            column: :id,
            name: "plan_tasks_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :assigned_to_user_id,
          references(:users,
            column: :id,
            name: "plan_tasks_assigned_to_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:plan_tasks, "plan_tasks_conversation_id_fkey")

    drop constraint(:plan_tasks, "plan_tasks_parent_id_fkey")

    drop constraint(:plan_tasks, "plan_tasks_assigned_to_user_id_fkey")

    drop table(:plan_tasks)

    drop_if_exists unique_index(:plan_task_pane_states, [:conversation_id, :user_id],
                     name: "plan_task_pane_states_unique_conversation_user_index"
                   )

    drop constraint(:plan_task_pane_states, "plan_task_pane_states_conversation_id_fkey")

    drop constraint(:plan_task_pane_states, "plan_task_pane_states_user_id_fkey")

    drop table(:plan_task_pane_states)
  end
end
