defmodule Magus.Repo.Migrations.AddAgentSecretCascadeDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:agent_secrets, "agent_secrets_custom_agent_id_fkey")

    alter table(:agent_secrets) do
      modify :custom_agent_id,
             references(:custom_agents,
               column: :id,
               name: "agent_secrets_custom_agent_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:agent_secrets, "agent_secrets_custom_agent_id_fkey")

    alter table(:agent_secrets) do
      modify :custom_agent_id,
             references(:custom_agents,
               column: :id,
               name: "agent_secrets_custom_agent_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
