defmodule Magus.Repo.Migrations.AddToolCallDataToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :tool_call_data, :map
    end
  end

  def down do
    alter table(:messages) do
      remove :tool_call_data
    end
  end
end
