defmodule Magus.Repo.Migrations.AddUserRegistrationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
      add :accepted_terms, :boolean, null: false, default: false
      add :accepted_age_requirement, :boolean, null: false, default: false
    end

    create unique_index(:users, [:display_name], name: "users_unique_display_name_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:display_name], name: "users_unique_display_name_index")

    alter table(:users) do
      remove :accepted_age_requirement
      remove :accepted_terms
      remove :name
    end
  end
end
