defmodule Magus.Repo.Migrations.CreateKnowledgeCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_collections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :external_id, :text, null: false
      add :external_path, :text
      add :sync_status, :text, null: false, default: "pending"
      add :sync_strategy, :text, null: false, default: "poll"
      add :sync_interval_minutes, :bigint, default: 60
      add :last_synced_at, :utc_datetime_usec
      add :content_updated_at, :utc_datetime_usec
      add :sync_cursor, :text
      add :item_count, :bigint, default: 0
      add :error_count, :bigint, default: 0
      add :last_error, :text
      add :settings, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_source_id,
          references(:knowledge_sources,
            column: :id,
            name: "knowledge_collections_knowledge_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:knowledge_collections, [:knowledge_source_id, :external_id],
             name: "knowledge_collections_unique_external_index"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_collections, [:knowledge_source_id, :external_id],
                     name: "knowledge_collections_unique_external_index"
                   )

    drop constraint(:knowledge_collections, "knowledge_collections_knowledge_source_id_fkey")

    drop table(:knowledge_collections)
  end
end
