defmodule Magus.Repo.Migrations.AddAssignedByToPlanTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_tasks) do
      add :assigned_by_custom_agent_id, :uuid
    end
  end

  def down do
    alter table(:plan_tasks) do
      remove :assigned_by_custom_agent_id
    end
  end
end
