defmodule Magus.Repo.Migrations.DropCostMultiplierGating do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_plans) do
      remove :max_cost_multiplier
    end

    alter table(:models) do
      remove :cost_multiplier
    end
  end

  def down do
    alter table(:models) do
      add :cost_multiplier, :decimal, null: false, default: "1.0"
    end

    alter table(:usage_plans) do
      add :max_cost_multiplier, :decimal
    end
  end
end
