defmodule Magus.Repo.Migrations.AddProviderToSandboxes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sandboxes) do
      add :provider, :text, default: "sprites"
      add :provider_data, :map, default: %{}
    end
  end

  def down do
    alter table(:sandboxes) do
      remove :provider_data
      remove :provider
    end
  end
end
