defmodule Magus.Repo.Migrations.AddUpdateLockedAction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_blocks) do
      remove :lock_version
    end
  end

  def down do
    alter table(:brain_blocks) do
      add :lock_version, :bigint, default: 0
    end
  end
end
