defmodule Magus.Repo.Migrations.AddWorkspaceOrganizationId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "workspaces_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:workspaces, "workspaces_organization_id_fkey")

    alter table(:workspaces) do
      remove :organization_id
    end
  end
end
