defmodule Magus.Repo.Migrations.Refactor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      remove :session_id
    end
  end

  def down do
    alter table(:messages) do
      add :session_id,
          references(:sessions,
            column: :id,
            name: "messages_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
