defmodule Magus.Repo.Migrations.AddInterestProfileResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:curation_interest_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :core_pillars, {:array, :map}, null: false, default: []
      add :discovery_interests, {:array, :map}, null: false, default: []
      add :negative_filters, {:array, :map}, null: false, default: []
      add :preferences, :map, null: false
      add :embedding, :vector, size: 1536

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "curation_interest_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:curation_interest_profiles, [:user_id],
             name: "curation_interest_profiles_unique_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:curation_interest_profiles, [:user_id],
                     name: "curation_interest_profiles_unique_user_index"
                   )

    drop constraint(:curation_interest_profiles, "curation_interest_profiles_user_id_fkey")

    drop table(:curation_interest_profiles)
  end
end
