defmodule Magus.Repo.Migrations.AddGenerationIdAndReconciledAtToMessageUsages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message_usages) do
      add :provider_generation_id, :text
      add :reconciled_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:message_usages) do
      remove :reconciled_at
      remove :provider_generation_id
    end
  end
end
