defmodule Magus.Repo.Migrations.CreateCurationTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:curation_inbox_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :url, :text, null: false
      add :content, :text
      add :author, :text
      add :published_at, :utc_datetime_usec
      add :metadata, :map, null: false, default: %{}
      add :content_hash, :text
      add :status, :text, null: false, default: "raw"
      add :content_embedding, :vector
      add :similarity_score, :float
      add :insight, :text
      add :curated_at, :utc_datetime_usec
      add :is_read, :boolean, null: false, default: false
      add :read_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "curation_inbox_items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_id, :uuid, null: false
    end

    create index(:curation_inbox_items, [:user_id, :inserted_at])

    create index(:curation_inbox_items, [:source_id, :content_hash])

    create index(:curation_inbox_items, [:user_id, :status])

    create table(:curation_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:curation_inbox_items) do
      modify :source_id,
             references(:curation_sources,
               column: :id,
               name: "curation_inbox_items_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:curation_inbox_items, [:source_id, :content_hash],
             name: "curation_inbox_items_unique_content_per_source_index"
           )

    alter table(:curation_sources) do
      add :name, :text, null: false
      add :source_type, :text, null: false
      add :config, :map, null: false, default: %{}
      add :is_active, :boolean, null: false, default: true
      add :fetch_interval_minutes, :bigint, null: false, default: 60
      add :priority, :bigint, null: false, default: 10
      add :next_fetch_at, :utc_datetime_usec
      add :last_fetched_at, :utc_datetime_usec
      add :last_error, :text
      add :consecutive_failures, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "curation_sources_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:curation_sources, [:user_id, :name],
             name: "curation_sources_unique_name_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:curation_sources, [:user_id, :name],
                     name: "curation_sources_unique_name_per_user_index"
                   )

    drop constraint(:curation_sources, "curation_sources_user_id_fkey")

    alter table(:curation_sources) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :consecutive_failures
      remove :last_error
      remove :last_fetched_at
      remove :next_fetch_at
      remove :priority
      remove :fetch_interval_minutes
      remove :is_active
      remove :config
      remove :source_type
      remove :name
    end

    drop_if_exists unique_index(:curation_inbox_items, [:source_id, :content_hash],
                     name: "curation_inbox_items_unique_content_per_source_index"
                   )

    drop constraint(:curation_inbox_items, "curation_inbox_items_source_id_fkey")

    alter table(:curation_inbox_items) do
      modify :source_id, :uuid
    end

    drop table(:curation_sources)

    drop constraint(:curation_inbox_items, "curation_inbox_items_user_id_fkey")

    drop_if_exists index(:curation_inbox_items, [:user_id, :status])

    drop_if_exists index(:curation_inbox_items, [:source_id, :content_hash])

    drop_if_exists index(:curation_inbox_items, [:user_id, :inserted_at])

    drop table(:curation_inbox_items)
  end
end
