defmodule Magus.Repo.Migrations.AddCurrentWorkspaceReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :current_workspace_id,
             references(:workspaces,
               column: :id,
               name: "users_current_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:users, [:current_workspace_id])
  end

  def down do
    drop_if_exists index(:users, [:current_workspace_id])

    drop constraint(:users, "users_current_workspace_id_fkey")

    alter table(:users) do
      modify :current_workspace_id, :uuid
    end
  end
end
