defmodule Magus.Repo.Migrations.AddNotificationsUserReadAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:notifications, [:user_id, :read_at])
  end

  def down do
    drop_if_exists index(:notifications, [:user_id, :read_at])
  end
end
