defmodule Magus.Repo.Migrations.AddModelRoleAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:model_role_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :disabled?, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :model_id,
          references(:models,
            column: :id,
            name: "model_role_assignments_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:model_role_assignments, [:role],
             name: "model_role_assignments_unique_role_index"
           )
  end

  def down do
    drop_if_exists unique_index(:model_role_assignments, [:role],
                     name: "model_role_assignments_unique_role_index"
                   )

    drop constraint(:model_role_assignments, "model_role_assignments_model_id_fkey")

    drop table(:model_role_assignments)
  end
end
