defmodule Magus.Repo.Migrations.TaskDismissedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_tasks) do
      add :dismissed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:plan_tasks) do
      remove :dismissed_at
    end
  end
end
