defmodule Magus.Repo.Migrations.MakeNotificationTitleOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notifications) do
      modify :title, :text, null: true
    end
  end

  def down do
    alter table(:notifications) do
      modify :title, :text, null: false
    end
  end
end
