defmodule Magus.Repo.Migrations.CreateAgentStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :agent_module, :text, null: false
      add :agent_id, :text, null: false
      add :state_data, :map, null: false
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agent_states, [:agent_module, :agent_id],
             name: "agent_states_agent_key_index"
           )

    create unique_index(:agent_states, [:id], name: "agent_states_id_index")
  end

  def down do
    drop_if_exists unique_index(:agent_states, [:id], name: "agent_states_id_index")

    drop_if_exists unique_index(:agent_states, [:agent_module, :agent_id],
                     name: "agent_states_agent_key_index"
                   )

    drop table(:agent_states)
  end
end
