defmodule Magus.Repo.Migrations.AddMcpServerProvenance do
  @moduledoc """
  Adds registry-import provenance columns to `mcp_servers`. All non-secret and
  safe on the `:viewer`-readable row. `source` defaults to "manual" so existing
  rows backfill correctly.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mcp_servers) do
      add :source, :text, null: false, default: "manual"
      add :registry_name, :text
      add :registry_version, :text
      add :description, :text
      add :repository_url, :text
    end
  end

  def down do
    alter table(:mcp_servers) do
      remove :repository_url
      remove :description
      remove :registry_version
      remove :registry_name
      remove :source
    end
  end
end
