defmodule Magus.Repo.Migrations.AddConversationFavorites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversation_favorites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "conversation_favorites_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_favorites_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:conversation_favorites, [:user_id, :conversation_id],
             name: "conversation_favorites_unique_user_conversation_favorite_index"
           )
  end

  def down do
    drop_if_exists unique_index(:conversation_favorites, [:user_id, :conversation_id],
                     name: "conversation_favorites_unique_user_conversation_favorite_index"
                   )

    drop constraint(:conversation_favorites, "conversation_favorites_user_id_fkey")

    drop constraint(:conversation_favorites, "conversation_favorites_conversation_id_fkey")

    drop table(:conversation_favorites)
  end
end
