defmodule Magus.Repo.Migrations.CreateResourceAccesses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resource_accesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :grantee_type, :text, null: false
      add :grantee_id, :uuid, null: false
      add :role, :text, null: false

      add :granted_by_id,
          references(:users,
            column: :id,
            name: "resource_accesses_granted_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :granted_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :resource_accesses,
             [:resource_type, :resource_id, :grantee_type, :grantee_id],
             name: "resource_accesses_unique_grant_index"
           )

    create index(:resource_accesses, [:grantee_type, :grantee_id])
    create index(:resource_accesses, [:resource_type, :resource_id])
  end

  def down do
    drop_if_exists index(:resource_accesses, [:resource_type, :resource_id])
    drop_if_exists index(:resource_accesses, [:grantee_type, :grantee_id])

    drop_if_exists unique_index(
                     :resource_accesses,
                     [:resource_type, :resource_id, :grantee_type, :grantee_id],
                     name: "resource_accesses_unique_grant_index"
                   )

    drop constraint(:resource_accesses, "resource_accesses_granted_by_id_fkey")

    drop table(:resource_accesses)
  end
end
