defmodule Magus.Repo.Migrations.IncreaseExtractionBudgetCeiling do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:super_brain_extraction_budget) do
      modify :ceiling_call_count, :bigint, default: 5000
    end
  end

  def down do
    alter table(:super_brain_extraction_budget) do
      modify :ceiling_call_count, :bigint, default: 100
    end
  end
end
