defmodule Magus.Repo.Migrations.AddUserContextStrategy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :context_strategy, :text
    end
  end

  def down do
    alter table(:users) do
      remove :context_strategy
    end
  end
end
