defmodule Magus.Repo.Migrations.AddIngestionEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :source_type, :text, null: false
      add :external_id, :text
      add :severity, :text, null: false, default: "info"
      add :title, :text
      add :content, :text, null: false
      add :metadata, :map, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false
      add :content_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_integration_id,
          references(:user_integrations,
            column: :id,
            name: "ingestion_entries_user_integration_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "ingestion_entries_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:ingestion_entries, [:user_integration_id, :content_hash],
             name: "ingestion_entries_unique_content_per_integration_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ingestion_entries, [:user_integration_id, :content_hash],
                     name: "ingestion_entries_unique_content_per_integration_index"
                   )

    drop constraint(:ingestion_entries, "ingestion_entries_user_integration_id_fkey")

    drop constraint(:ingestion_entries, "ingestion_entries_user_id_fkey")

    drop table(:ingestion_entries)
  end
end
