defmodule Magus.Repo.Migrations.RenameTiersAndAddMaxRoutingTier do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # 1. Add max_routing_tier column to usage_plans
    alter table(:usage_plans) do
      add :max_routing_tier, :text, null: false, default: "simple"
    end

    # 2. Seed max_routing_tier for existing plans
    execute """
    UPDATE usage_plans SET max_routing_tier = CASE
      WHEN key = 'free' THEN 'simple'
      WHEN key = 'starter' THEN 'complex'
      WHEN key LIKE 'pro%' THEN 'complex'
      ELSE 'simple'
    END
    """

    # 3. Rename existing tier values in routing_slots: free→simple, starter→standard, pro→complex
    execute """
    UPDATE routing_slots SET tier = CASE tier
      WHEN 'free' THEN 'simple'
      WHEN 'starter' THEN 'standard'
      WHEN 'pro' THEN 'complex'
      ELSE tier
    END
    """
  end

  def down do
    # Reverse the tier rename in routing_slots
    execute """
    UPDATE routing_slots SET tier = CASE tier
      WHEN 'simple' THEN 'free'
      WHEN 'standard' THEN 'starter'
      WHEN 'complex' THEN 'pro'
      ELSE tier
    END
    """

    alter table(:usage_plans) do
      remove :max_routing_tier
    end
  end
end
