defmodule Magus.Repo.Migrations.NilifyConversationSkillApprovalApprovedBy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(
           :conversation_skill_approvals,
           "conversation_skill_approvals_approved_by_id_fkey"
         )

    alter table(:conversation_skill_approvals) do
      modify :approved_by_id,
             references(:users,
               column: :id,
               name: "conversation_skill_approvals_approved_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(
           :conversation_skill_approvals,
           "conversation_skill_approvals_approved_by_id_fkey"
         )

    alter table(:conversation_skill_approvals) do
      modify :approved_by_id,
             references(:users,
               column: :id,
               name: "conversation_skill_approvals_approved_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
