defmodule Magus.Repo.Migrations.AddMemoryConfidenceKindAgentScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_local_requires_conversation
    """)

    alter table(:memories) do
      add :confidence, :float, null: false, default: 1.0
      add :kind, :text, null: false, default: "general"

      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "memories_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:memories, [:custom_agent_id, :name],
             name: "memories_unique_name_per_agent_index",
             where: "(is_active = true AND scope = 'agent')"
           )

    execute("""
    ALTER TABLE memories ADD CONSTRAINT memories_agent_scope_requires_agent CHECK (scope != 'agent' OR custom_agent_id IS NOT NULL)
    """)

    execute("""
    ALTER TABLE memories ADD CONSTRAINT memories_local_requires_conversation CHECK (scope IN ('global', 'agent') OR conversation_id IS NOT NULL)
    """)
  end

  def down do
    execute("""
    ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_local_requires_conversation
    """)

    execute("""
    ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_agent_scope_requires_agent
    """)

    drop_if_exists unique_index(:memories, [:custom_agent_id, :name],
                     name: "memories_unique_name_per_agent_index"
                   )

    drop constraint(:memories, "memories_custom_agent_id_fkey")

    alter table(:memories) do
      remove :custom_agent_id
      remove :kind
      remove :confidence
    end

    execute("""
    ALTER TABLE memories ADD CONSTRAINT memories_local_requires_conversation CHECK (scope = 'global' OR conversation_id IS NOT NULL)
    """)
  end
end
