defmodule Magus.Repo.Migrations.AddCustomAgents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:custom_agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :icon, :text
      add :instructions, :text
      add :conversation_starters, {:array, :text}, default: []
      add :chat_mode, :text
      add :disabled_tool_categories, {:array, :text}, default: []
      add :pre_loaded_skills, {:array, :text}, default: []
      add :sampling_settings, :map
      add :max_iterations, :bigint, default: 10
      add :is_default, :boolean, default: false
      add :is_public, :boolean, default: false
      add :use_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "custom_agents_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :model_id,
          references(:models,
            column: :id,
            name: "custom_agents_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :image_model_id,
          references(:models,
            column: :id,
            name: "custom_agents_image_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :video_model_id,
          references(:models,
            column: :id,
            name: "custom_agents_video_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:custom_agents, [:user_id],
             name: "custom_agents_unique_default_index",
             where: "(is_default = true)"
           )

    alter table(:conversations) do
      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "conversations_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_custom_agent_id_fkey")

    alter table(:conversations) do
      remove :custom_agent_id
    end

    drop_if_exists unique_index(:custom_agents, [:user_id],
                     name: "custom_agents_unique_default_index"
                   )

    drop constraint(:custom_agents, "custom_agents_user_id_fkey")

    drop constraint(:custom_agents, "custom_agents_model_id_fkey")

    drop constraint(:custom_agents, "custom_agents_image_model_id_fkey")

    drop constraint(:custom_agents, "custom_agents_video_model_id_fkey")

    drop table(:custom_agents)
  end
end
