defmodule Magus.Repo.Migrations.AddOwnerUserIdIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:models, [:owner_user_id])

    create index(:model_providers, [:owner_user_id])
  end

  def down do
    drop_if_exists index(:model_providers, [:owner_user_id])

    drop_if_exists index(:models, [:owner_user_id])
  end
end
