defmodule Magus.Repo.Migrations.AddDueAtAndRecurrenceToTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_tasks) do
      add :due_at, :utc_datetime_usec
      add :recurrence, :map
    end
  end

  def down do
    alter table(:plan_tasks) do
      remove :recurrence
      remove :due_at
    end
  end
end
