defmodule Magus.Repo.Migrations.AddReconciliationStatusToMessageUsages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message_usages) do
      add :reconciliation_status, :text, null: false, default: "not_required"
    end
  end

  def down do
    alter table(:message_usages) do
      remove :reconciliation_status
    end
  end
end
