defmodule Magus.Repo.Migrations.CreateMcpServerCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mcp_server_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :auth_kind, :text, null: false, default: "static_header"
      add :static_headers, :binary
      add :oauth_tokens, :binary
      add :oauth_expires_at, :utc_datetime_usec
      add :oauth_client, :binary
      add :status, :text, null: false, default: "disconnected"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mcp_server_id,
          references(:mcp_servers,
            column: :id,
            name: "mcp_server_credentials_mcp_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "mcp_server_credentials_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:mcp_server_credentials, [:mcp_server_id, :user_id],
             name: "mcp_server_credentials_unique_server_user_index"
           )
  end

  def down do
    drop constraint(:mcp_server_credentials, "mcp_server_credentials_mcp_server_id_fkey")

    drop constraint(:mcp_server_credentials, "mcp_server_credentials_user_id_fkey")

    drop_if_exists unique_index(:mcp_server_credentials, [:mcp_server_id, :user_id],
                     name: "mcp_server_credentials_unique_server_user_index"
                   )

    drop table(:mcp_server_credentials)
  end
end
