defmodule Magus.Repo.Migrations.AddWorkspaceToPrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "custom_agents_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:prompts) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "prompts_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:files) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "files_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:files, "files_workspace_id_fkey")

    alter table(:files) do
      remove :workspace_id
    end

    drop constraint(:prompts, "prompts_workspace_id_fkey")

    alter table(:prompts) do
      remove :workspace_id
    end

    drop constraint(:custom_agents, "custom_agents_workspace_id_fkey")

    alter table(:custom_agents) do
      remove :workspace_id
    end
  end
end
