defmodule Magus.Repo.Migrations.AddMemoryAssociationsToDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memory_associations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :weight, :float, null: false, default: 0.1
      add :last_reinforced_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :memory_a_id,
          references(:memories,
            column: :id,
            name: "memory_associations_memory_a_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :memory_b_id,
          references(:memories,
            column: :id,
            name: "memory_associations_memory_b_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memory_associations, [:memory_a_id, :memory_b_id],
             name: "memory_associations_unique_pair_index"
           )

    execute("""
    ALTER TABLE memory_associations ADD CONSTRAINT memory_associations_ordered CHECK (memory_a_id < memory_b_id)
    """)
  end

  def down do
    execute("""
    ALTER TABLE memory_associations DROP CONSTRAINT IF EXISTS memory_associations_ordered
    """)

    drop_if_exists unique_index(:memory_associations, [:memory_a_id, :memory_b_id],
                     name: "memory_associations_unique_pair_index"
                   )

    drop constraint(:memory_associations, "memory_associations_memory_a_id_fkey")

    drop constraint(:memory_associations, "memory_associations_memory_b_id_fkey")

    drop table(:memory_associations)
  end
end
