defmodule Magus.Repo.Migrations.AddSandboxSecrets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sandbox_secrets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false
      add :value, :binary, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "sandbox_secrets_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:sandbox_secrets, [:user_id, :key],
             name: "sandbox_secrets_unique_key_per_user_index"
           )
  end

  def down do
    drop constraint(:sandbox_secrets, "sandbox_secrets_user_id_fkey")

    drop_if_exists unique_index(:sandbox_secrets, [:user_id, :key],
                     name: "sandbox_secrets_unique_key_per_user_index"
                   )

    drop table(:sandbox_secrets)
  end
end
