defmodule Magus.Repo.Migrations.CreateDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:drafts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :content, :text, null: false, default: ""
      add :status, :text, null: false, default: "draft"
      add :version, :bigint, null: false, default: 1
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "drafts_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "drafts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:drafts, [:conversation_id],
             name: "drafts_unique_draft_per_conversation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:drafts, [:conversation_id],
                     name: "drafts_unique_draft_per_conversation_index"
                   )

    drop constraint(:drafts, "drafts_conversation_id_fkey")

    drop constraint(:drafts, "drafts_user_id_fkey")

    drop table(:drafts)
  end
end
