defmodule Magus.Repo.Migrations.AddExtractionDueAtToConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :extraction_due_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:conversations) do
      remove :extraction_due_at
    end
  end
end
