defmodule Magus.Repo.Migrations.AddPaperTrailActor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspace_members_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "workspace_members_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:workspaces_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "workspaces_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:workspaces_versions, "workspaces_versions_user_id_fkey")

    alter table(:workspaces_versions) do
      remove :user_id
    end

    drop constraint(:workspace_members_versions, "workspace_members_versions_user_id_fkey")

    alter table(:workspace_members_versions) do
      remove :user_id
    end
  end
end
