defmodule Magus.Repo.Migrations.AddPageKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      add :kind, :text, null: false, default: "page"
    end
  end

  def down do
    alter table(:brain_pages) do
      remove :kind
    end
  end
end
