defmodule Magus.Repo.Migrations.AddMessagesConversationInsertedAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:messages, [:conversation_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:messages, [:conversation_id, :inserted_at])
  end
end
