defmodule Magus.Repo.Migrations.CreateWorkspaces do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      remove :owner_id
      remove :token_limit
      remove :total_tokens_used
      remove :settings
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :slug, :text, null: false
      add :stripe_customer_id, :text
      add :stripe_subscription_id, :text
      add :base_seats, :bigint, null: false, default: 5
      add :max_seats, :bigint
      add :allowed_model_ids, {:array, :uuid}
      add :is_active, :boolean, null: false, default: true

      add :plan_id,
          references(:usage_plans,
            column: :id,
            name: "workspaces_plan_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :default_agent_id,
          references(:custom_agents,
            column: :id,
            name: "workspaces_default_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    alter table(:workspace_members) do
      remove :invited_by_id
      remove :accepted_at
      remove :invited_at
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :is_active, :boolean, null: false, default: true
    end

    drop_if_exists unique_index(:workspace_members, [:workspace_id, :user_id],
                     name: "workspace_members_unique_membership_index"
                   )
  end

  def down do
    create unique_index(:workspace_members, [:workspace_id, :user_id],
             name: "workspace_members_unique_membership_index"
           )

    alter table(:workspace_members) do
      remove :is_active
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :invited_at, :utc_datetime_usec
      add :accepted_at, :utc_datetime_usec

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "workspace_members_invited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    drop constraint(:workspaces, "workspaces_plan_id_fkey")

    drop constraint(:workspaces, "workspaces_default_agent_id_fkey")

    alter table(:workspaces) do
      remove :default_agent_id
      remove :plan_id
      remove :is_active
      remove :allowed_model_ids
      remove :max_seats
      remove :base_seats
      remove :stripe_subscription_id
      remove :stripe_customer_id
      remove :slug
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :settings, :map, null: false, default: %{}
      add :total_tokens_used, :bigint, null: false, default: 0
      add :token_limit, :bigint

      add :owner_id,
          references(:users,
            column: :id,
            name: "workspaces_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
