defmodule Magus.Repo.Migrations.AddConversationModeToUserIntegrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_integrations) do
      add :conversation_mode, :text, default: "single"
      add :reply_enabled, :boolean, default: true

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "user_integrations_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:user_integrations, "user_integrations_conversation_id_fkey")

    alter table(:user_integrations) do
      remove :conversation_id
      remove :reply_enabled
      remove :conversation_mode
    end
  end
end
