defmodule Magus.Repo.Migrations.UnifiedCredits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_plans) do
      remove :monthly_videos
      remove :monthly_images
      remove :daily_premium_messages
      remove :daily_standard_messages
      remove :daily_basic_messages
      add :daily_credits, :bigint
      add :max_cost_multiplier, :decimal
    end

    alter table(:models) do
      remove :pricing_tier
    end

    alter table(:message_usages) do
      add :credits_consumed, :bigint, null: false, default: 0
    end

    # Backfill existing message usages using the model's actual cost_multiplier.
    # For video generation, multiply by duration (fallback 5s if not recorded).
    # For all other types, use ceil(cost_multiplier).
    # Records without a matching model get credits_consumed = 1.
    execute("""
    UPDATE message_usages mu
    SET credits_consumed = CEIL(
      COALESCE(m.cost_multiplier, 1) *
      CASE WHEN mu.usage_type = 'video_generation'
        THEN COALESCE(mu.video_duration, 5)
        ELSE 1
      END
    )
    FROM models m
    WHERE mu.model_id = m.id
      AND mu.billable = true
      AND mu.credits_consumed = 0
    """)

    # Catch any billable records with no matching model (e.g. deleted models)
    execute("""
    UPDATE message_usages SET credits_consumed = 1
    WHERE billable = true AND credits_consumed = 0
    """)

    alter table(:user_usage_overrides) do
      remove :bonus_monthly_videos
      remove :bonus_monthly_images
      remove :bonus_daily_premium_messages
      remove :bonus_daily_standard_messages
      remove :bonus_daily_basic_messages
      add :bonus_daily_credits, :bigint, default: 0
    end
  end

  def down do
    alter table(:user_usage_overrides) do
      remove :bonus_daily_credits
      add :bonus_daily_basic_messages, :bigint, default: 0
      add :bonus_daily_standard_messages, :bigint, default: 0
      add :bonus_daily_premium_messages, :bigint, default: 0
      add :bonus_monthly_images, :bigint, default: 0
      add :bonus_monthly_videos, :bigint, default: 0
    end

    alter table(:message_usages) do
      remove :credits_consumed
    end

    alter table(:models) do
      add :pricing_tier, :text, null: false, default: "standard"
    end

    alter table(:usage_plans) do
      remove :max_cost_multiplier
      remove :daily_credits
      add :daily_basic_messages, :bigint
      add :daily_standard_messages, :bigint
      add :daily_premium_messages, :bigint
      add :monthly_images, :bigint
      add :monthly_videos, :bigint
    end
  end
end
