defmodule Magus.Repo.Migrations.AddMemorySourceIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:memory_sources, [:memory_id, :source_type, :source_uri],
             name: "memory_sources_memory_source_lookup_index"
           )
  end

  def down do
    drop_if_exists unique_index(:memory_sources, [:memory_id, :source_type, :source_uri],
                     name: "memory_sources_memory_source_lookup_index"
                   )
  end
end
