defmodule Magus.Repo.Migrations.CustomApiPartialUniqueIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:user_integrations, [:custom_agent_id, :provider_key],
                     name: "user_integrations_unique_agent_provider_index"
                   )

    create unique_index(:user_integrations, [:custom_agent_id, :provider_key],
             where: "provider_key != 'custom_api'",
             name: "user_integrations_unique_agent_non_custom_api_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_integrations, [:custom_agent_id, :provider_key],
                     name: "user_integrations_unique_agent_non_custom_api_index"
                   )

    create unique_index(:user_integrations, [:custom_agent_id, :provider_key],
             name: "user_integrations_unique_agent_provider_index"
           )
  end
end
