defmodule Magus.Repo.Migrations.AddConversationCompanions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversation_companions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "conversation_companions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_companions_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:conversation_companions, [:user_id, :resource_type, :resource_id],
             name: "conversation_companions_unique_companion_per_resource_index"
           )

    create unique_index(:conversation_companions, [:conversation_id],
             name: "conversation_companions_unique_conversation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:conversation_companions, [:conversation_id],
                     name: "conversation_companions_unique_conversation_index"
                   )

    drop_if_exists unique_index(
                     :conversation_companions,
                     [:user_id, :resource_type, :resource_id],
                     name: "conversation_companions_unique_companion_per_resource_index"
                   )

    drop constraint(:conversation_companions, "conversation_companions_user_id_fkey")

    drop constraint(:conversation_companions, "conversation_companions_conversation_id_fkey")

    drop table(:conversation_companions)
  end
end
