defmodule Magus.Repo.Migrations.AddSandboxConversationId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :sandbox_conversation_id,
          references(:conversations,
            column: :id,
            name: "conversations_sandbox_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:conversations, [:sandbox_conversation_id])
  end

  def down do
    drop_if_exists index(:conversations, [:sandbox_conversation_id])

    drop constraint(:conversations, "conversations_sandbox_conversation_id_fkey")

    alter table(:conversations) do
      remove :sandbox_conversation_id
    end
  end
end
