defmodule Magus.Repo.Migrations.CreateSkills do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :display_name, :text
      add :description, :text, null: false
      add :body, :text
      add :requested_tools, {:array, :text}, default: []
      add :required_secrets, {:array, :map}, default: []
      add :runtime_hints, :map, default: %{}
      add :metadata, :map, default: %{}
      add :version, :text
      add :license, :text
      add :compatibility, :text
      add :icon, :text
      add :color, :text
      add :source_format, :text, null: false, default: "skill_md"
      add :source_url, :text
      add :has_executable_bundle, :boolean, null: false, default: false
      add :bundle_path, :text
      add :bundle_backend, :text
      add :bundle_byte_size, :bigint
      add :file_manifest, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "skills_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "skills_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:skills, "skills_user_id_fkey")

    drop constraint(:skills, "skills_workspace_id_fkey")

    drop table(:skills)
  end
end
