defmodule Magus.Repo.Migrations.EnhancePromptDetailPage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:prompts) do
      add :description, :text
      add :user_message_template, :text
      add :version, :text, default: "1.0"
      add :estimated_tokens, :text
      add :language, :text, default: "en"
      add :view_count, :bigint, default: 0
      add :embedding, :vector
    end

    create table(:prompt_examples, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :variables, :map, null: false, default: %{}
      add :description, :text
      add :order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :prompt_id,
          references(:prompts,
            column: :id,
            name: "prompt_examples_prompt_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:prompt_examples, "prompt_examples_prompt_id_fkey")

    drop table(:prompt_examples)

    alter table(:prompts) do
      remove :embedding
      remove :view_count
      remove :language
      remove :estimated_tokens
      remove :version
      remove :user_message_template
      remove :description
    end
  end
end
