defmodule Magus.Repo.Migrations.AddSandboxFilesAndUploads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sandbox_uploads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :filename, :text, null: false
      add :original_path, :text, null: false
      add :sandbox_path, :text, null: false
      add :size_bytes, :bigint
      add :mime_type, :text, default: "application/octet-stream"
      add :copied_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sandbox_id,
          references(:sandboxes,
            column: :id,
            name: "sandbox_uploads_sandbox_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_file_id,
          references(:files,
            column: :id,
            name: "sandbox_uploads_source_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:sandbox_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :filename, :text, null: false
      add :path, :text, null: false
      add :size_bytes, :bigint
      add :mime_type, :text, default: "application/octet-stream"
      add :download_token, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sandbox_id,
          references(:sandboxes,
            column: :id,
            name: "sandbox_files_sandbox_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :execution_id,
          references(:sandbox_executions,
            column: :id,
            name: "sandbox_files_execution_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:sandbox_files, [:download_token],
             name: "sandbox_files_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sandbox_files, [:download_token],
                     name: "sandbox_files_unique_token_index"
                   )

    drop constraint(:sandbox_files, "sandbox_files_sandbox_id_fkey")

    drop constraint(:sandbox_files, "sandbox_files_execution_id_fkey")

    drop table(:sandbox_files)

    drop constraint(:sandbox_uploads, "sandbox_uploads_sandbox_id_fkey")

    drop constraint(:sandbox_uploads, "sandbox_uploads_source_file_id_fkey")

    drop table(:sandbox_uploads)
  end
end
