defmodule Magus.Repo.Migrations.AddEnabledToolsToUserIntegrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_integrations) do
      add :enabled_tools, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:user_integrations) do
      remove :enabled_tools
    end
  end
end
