defmodule Magus.Repo.Migrations.RenameMemoryScopeGlobalToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Drop the old check constraint first so the data update doesn't violate it
    execute("""
    ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_local_requires_conversation
    """)

    # Data migration: rename scope 'global' -> 'user' for existing rows
    execute("""
    UPDATE memories SET scope = 'user' WHERE scope = 'global'
    """)

    drop_if_exists unique_index(:memories, [:user_id, :name],
                     name: "memories_unique_global_name_per_user_index"
                   )

    create unique_index(:memories, [:user_id, :name],
             name: "memories_unique_user_name_per_user_index",
             where: "(is_active = true AND scope = 'user')"
           )

    execute("""
    ALTER TABLE memories ADD CONSTRAINT memories_local_requires_conversation CHECK (scope IN ('user', 'agent') OR conversation_id IS NOT NULL)
    """)
  end

  def down do
    # Reverse data migration: rename scope 'user' -> 'global'
    execute("""
    UPDATE memories SET scope = 'global' WHERE scope = 'user'
    """)

    execute("""
    ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_local_requires_conversation
    """)

    drop_if_exists unique_index(:memories, [:user_id, :name],
                     name: "memories_unique_user_name_per_user_index"
                   )

    create unique_index(:memories, [:user_id, :name],
             name: "memories_unique_global_name_per_user_index",
             where: "(is_active = true AND scope = 'global')"
           )

    execute("""
    ALTER TABLE memories ADD CONSTRAINT memories_local_requires_conversation CHECK (scope IN ('global', 'agent') OR conversation_id IS NOT NULL)
    """)
  end
end
