defmodule Magus.Repo.Migrations.AddBrainPagesDeletedAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:brain_pages, [:deleted_at], name: "brain_pages_deleted_at_index")
  end

  def down do
    drop_if_exists index(:brain_pages, [:deleted_at], name: "brain_pages_deleted_at_index")
  end
end
