defmodule Magus.Repo.Migrations.CreateSandboxTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sandboxes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :sprite_id, :text
      add :sprite_url, :text
      add :checkpoint_id, :text
      add :installed_packages, {:array, :text}, default: []
      add :total_executions, :bigint, default: 0
      add :total_cost_usd, :decimal, default: "0"
      add :last_executed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "sandboxes_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :state, :text, null: false, default: "uninitialized"
    end

    create unique_index(:sandboxes, [:conversation_id],
             name: "sandboxes_unique_conversation_index"
           )

    create table(:sandbox_executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :code, :text
      add :description, :text
      add :stdout, :text
      add :stderr, :text
      add :exit_code, :bigint
      add :duration_ms, :bigint
      add :estimated_cost_usd, :decimal
      add :files_created, {:array, :text}, default: []
      add :error_type, :text
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sandbox_id,
          references(:sandboxes,
            column: :id,
            name: "sandbox_executions_sandbox_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :message_id,
          references(:messages,
            column: :id,
            name: "sandbox_executions_message_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:sandbox_executions, "sandbox_executions_sandbox_id_fkey")

    drop constraint(:sandbox_executions, "sandbox_executions_message_id_fkey")

    drop table(:sandbox_executions)

    drop_if_exists unique_index(:sandboxes, [:conversation_id],
                     name: "sandboxes_unique_conversation_index"
                   )

    drop constraint(:sandboxes, "sandboxes_conversation_id_fkey")

    drop table(:sandboxes)
  end
end
