defmodule Magus.Repo.Migrations.AddAgentSecrets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_secrets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false
      add :value, :binary, null: false
      add :scope, :text, null: false, default: "sandbox_env"
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "agent_secrets_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:agent_secrets, [:custom_agent_id, :key],
             name: "agent_secrets_unique_key_per_agent_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_secrets, [:custom_agent_id, :key],
                     name: "agent_secrets_unique_key_per_agent_index"
                   )

    drop constraint(:agent_secrets, "agent_secrets_custom_agent_id_fkey")

    drop table(:agent_secrets)
  end
end
