defmodule Magus.Repo.Migrations.ChangeFilesCreatedToMapArray do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Drop the old default, clear data, change type, set new default
    execute "ALTER TABLE sandbox_executions ALTER COLUMN files_created DROP DEFAULT"
    execute "UPDATE sandbox_executions SET files_created = NULL"

    execute "ALTER TABLE sandbox_executions ALTER COLUMN files_created TYPE jsonb[] USING '{}'::jsonb[]"

    execute "ALTER TABLE sandbox_executions ALTER COLUMN files_created SET DEFAULT '{}'::jsonb[]"
  end

  def down do
    execute "ALTER TABLE sandbox_executions ALTER COLUMN files_created DROP DEFAULT"
    execute "UPDATE sandbox_executions SET files_created = NULL"

    execute "ALTER TABLE sandbox_executions ALTER COLUMN files_created TYPE text[] USING '{}'::text[]"

    execute "ALTER TABLE sandbox_executions ALTER COLUMN files_created SET DEFAULT '{}'::text[]"
  end
end
