defmodule Magus.Repo.Migrations.PortPlanDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:plan_task_dependencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:plan_tasks,
            column: :id,
            name: "plan_task_dependencies_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :depends_on_id,
          references(:plan_tasks,
            column: :id,
            name: "plan_task_dependencies_depends_on_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:plan_task_dependencies, [:task_id, :depends_on_id],
             name: "plan_task_dependencies_unique_edge_index"
           )

    create table(:plan_task_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :brain_page_id, :uuid, null: false
      add :kind, :text, null: false
      add :actor_label, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:plan_tasks,
            column: :id,
            name: "plan_task_events_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:plan_tasks) do
      modify :conversation_id, :uuid, null: true
      add :priority, :text, null: false, default: "normal"
      add :claimed_at, :utc_datetime_usec
      add :lease_expires_at, :utc_datetime_usec
      add :created_by_label, :text

      add :brain_page_id,
          references(:brain_pages,
            column: :id,
            name: "plan_tasks_brain_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create constraint(:plan_tasks, :plan_tasks_exactly_one_container,
             check: """
               (conversation_id IS NULL) <> (brain_page_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:plan_tasks, :plan_tasks_exactly_one_container)

    drop constraint(:plan_tasks, "plan_tasks_brain_page_id_fkey")

    alter table(:plan_tasks) do
      remove :brain_page_id
      remove :created_by_label
      remove :lease_expires_at
      remove :claimed_at
      remove :priority
      modify :conversation_id, :uuid, null: false
    end

    drop constraint(:plan_task_events, "plan_task_events_task_id_fkey")

    drop table(:plan_task_events)

    drop constraint(:plan_task_dependencies, "plan_task_dependencies_task_id_fkey")

    drop constraint(:plan_task_dependencies, "plan_task_dependencies_depends_on_id_fkey")

    drop_if_exists unique_index(:plan_task_dependencies, [:task_id, :depends_on_id],
                     name: "plan_task_dependencies_unique_edge_index"
                   )

    drop table(:plan_task_dependencies)
  end
end
