defmodule Magus.Repo.Migrations.AddNextScheduledAtToCustomAgents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :next_scheduled_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :next_scheduled_at
    end
  end
end
