defmodule Magus.Repo.Migrations.BrainMdPhaseA do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      add :body, :text
      add :lock_version, :bigint, null: false, default: 0
      add :frontmatter, :map, null: false, default: %{}
    end

    # Generated full-text-search column over the body. Mirrors the pattern in
    # AddBlockTextSearch (brain_blocks.search_vector). The matching GIN index
    # is created concurrently in the sibling migration so the index build
    # doesn't lock writes.
    execute(
      """
      ALTER TABLE brain_pages
      ADD COLUMN search_vector tsvector
      GENERATED ALWAYS AS (to_tsvector('english', coalesce(body, ''))) STORED
      """,
      "ALTER TABLE brain_pages DROP COLUMN IF EXISTS search_vector"
    )

    create table(:brain_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :url, :text, null: false
      add :title, :text
      add :description, :text
      add :author, :text
      add :source_type, :text, default: "web"
      add :ingest_status, :text, null: false, default: "pending"
      add :ingested_content, :text
      add :ingest_error, :text
      add :ingested_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brain_id,
          references(:brains,
            column: :id,
            name: "brain_sources_brain_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:brain_sources, [:brain_id, :url],
             name: "brain_sources_unique_brain_url_index"
           )

    create table(:brain_page_chunks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :index, :bigint, null: false
      add :content, :text, null: false
      add :token_count, :bigint
      # Explicit dimensions are required by HNSW, which is built in the
      # sibling concurrent-indexes migration. text-embedding-3-small = 1536.
      add :embedding, :"vector(1536)"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_page_chunks_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:brain_page_chunks, [:page_id, :index],
             name: "brain_page_chunks_unique_page_index_index"
           )

    create table(:brain_page_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :target_title_at_link_time, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_page_links_source_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :target_page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_page_links_target_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:brain_page_links, [:target_page_id],
             name: "brain_page_links_target_page_id_index"
           )

    create unique_index(:brain_page_links, [:source_page_id, :target_page_id],
             name: "brain_page_links_unique_source_target_index"
           )

    create table(:brain_page_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_page_sources_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :source_id,
          references(:brain_sources,
            column: :id,
            name: "brain_page_sources_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:brain_page_sources, [:page_id, :source_id],
             name: "brain_page_sources_unique_page_source_index"
           )

    create table(:brain_pages_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "brain_pages_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:brain_page_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tag, :text, null: false
      add :source, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_page_tags_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :brain_id,
          references(:brains,
            column: :id,
            name: "brain_page_tags_brain_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:brain_page_tags, [:brain_id, :tag], name: "brain_page_tags_brain_id_tag_index")

    create unique_index(:brain_page_tags, [:page_id, :tag],
             name: "brain_page_tags_unique_page_tag_index"
           )

    create table(:brain_source_chunks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :index, :bigint, null: false
      add :content, :text, null: false
      add :token_count, :bigint
      # Explicit dimensions are required by HNSW, which is built in the
      # sibling concurrent-indexes migration. text-embedding-3-small = 1536.
      add :embedding, :"vector(1536)"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_id,
          references(:brain_sources,
            column: :id,
            name: "brain_source_chunks_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:brain_source_chunks, [:source_id, :index],
             name: "brain_source_chunks_unique_source_index_index"
           )
  end

  def down do
    drop_if_exists unique_index(:brain_source_chunks, [:source_id, :index],
                     name: "brain_source_chunks_unique_source_index_index"
                   )

    drop constraint(:brain_source_chunks, "brain_source_chunks_source_id_fkey")

    drop table(:brain_source_chunks)

    drop_if_exists unique_index(:brain_page_tags, [:page_id, :tag],
                     name: "brain_page_tags_unique_page_tag_index"
                   )

    drop constraint(:brain_page_tags, "brain_page_tags_page_id_fkey")

    drop constraint(:brain_page_tags, "brain_page_tags_brain_id_fkey")

    drop_if_exists index(:brain_page_tags, [:brain_id, :tag],
                     name: "brain_page_tags_brain_id_tag_index"
                   )

    drop table(:brain_page_tags)

    drop constraint(:brain_pages_versions, "brain_pages_versions_user_id_fkey")

    drop table(:brain_pages_versions)

    drop_if_exists unique_index(:brain_page_sources, [:page_id, :source_id],
                     name: "brain_page_sources_unique_page_source_index"
                   )

    drop constraint(:brain_page_sources, "brain_page_sources_page_id_fkey")

    drop constraint(:brain_page_sources, "brain_page_sources_source_id_fkey")

    drop table(:brain_page_sources)

    drop_if_exists unique_index(:brain_page_links, [:source_page_id, :target_page_id],
                     name: "brain_page_links_unique_source_target_index"
                   )

    drop constraint(:brain_page_links, "brain_page_links_source_page_id_fkey")

    drop constraint(:brain_page_links, "brain_page_links_target_page_id_fkey")

    drop_if_exists index(:brain_page_links, [:target_page_id],
                     name: "brain_page_links_target_page_id_index"
                   )

    drop table(:brain_page_links)

    drop_if_exists unique_index(:brain_page_chunks, [:page_id, :index],
                     name: "brain_page_chunks_unique_page_index_index"
                   )

    drop constraint(:brain_page_chunks, "brain_page_chunks_page_id_fkey")

    drop table(:brain_page_chunks)

    drop_if_exists unique_index(:brain_sources, [:brain_id, :url],
                     name: "brain_sources_unique_brain_url_index"
                   )

    drop constraint(:brain_sources, "brain_sources_brain_id_fkey")

    drop table(:brain_sources)

    # search_vector is a generated column depending on body — drop it before body.
    execute "ALTER TABLE brain_pages DROP COLUMN IF EXISTS search_vector"

    alter table(:brain_pages) do
      remove_if_exists :frontmatter, :map
      remove_if_exists :lock_version, :bigint
      remove_if_exists :body, :text
    end
  end
end
