defmodule Magus.Repo.Migrations.AddTeamSeatsToUsagePlans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_plans) do
      add :team_seats, :bigint
      add :extra_seat_stripe_price_id, :text
    end
  end

  def down do
    alter table(:usage_plans) do
      remove :extra_seat_stripe_price_id
      remove :team_seats
    end
  end
end
