defmodule Magus.Repo.Migrations.AddSuperBrainExtractionBudget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:super_brain_extraction_budget, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :user_id, :uuid, null: false
      add :date, :date, null: false
      add :llm_call_count, :bigint, default: 0
      add :llm_cost_cents, :bigint, default: 0
      add :ceiling_call_count, :bigint, default: 100

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:super_brain_extraction_budget, [:user_id, :date],
             name: "super_brain_extraction_budget_unique_user_date_index"
           )
  end

  def down do
    drop_if_exists unique_index(:super_brain_extraction_budget, [:user_id, :date],
                     name: "super_brain_extraction_budget_unique_user_date_index"
                   )

    drop table(:super_brain_extraction_budget)
  end
end
