defmodule Magus.Repo.Migrations.AddContextWindows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:context_windows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :strategy, :text
      add :window_start_at, :utc_datetime_usec
      add :summary, :text
      add :summary_message_count, :bigint, null: false, default: 0
      add :last_breakdown, :map
      add :last_total_tokens, :bigint
      add :last_actual_input_tokens, :bigint
      add :last_cached_tokens, :bigint
      add :last_model_key, :text
      add :last_max_context, :bigint
      add :compaction_status, :text, null: false, default: "idle"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "context_windows_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :window_start_message_id,
          references(:messages,
            column: :id,
            name: "context_windows_window_start_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:context_windows, [:conversation_id],
             name: "context_windows_unique_conversation_index"
           )
  end

  def down do
    drop constraint(:context_windows, "context_windows_conversation_id_fkey")

    drop constraint(:context_windows, "context_windows_window_start_message_id_fkey")

    drop_if_exists unique_index(:context_windows, [:conversation_id],
                     name: "context_windows_unique_conversation_index"
                   )

    drop table(:context_windows)
  end
end
