defmodule Magus.Repo.Migrations.AddCustomAgentPauseReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :pause_reason, :text
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :pause_reason
    end
  end
end
