defmodule Magus.Repo.Migrations.AddAgentRunIdempotencyIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # An unnamed partial unique index on `idempotency_key` already exists
    # (from the 20260301090000 migration that introduced this table), but it
    # was never declared as an Ash `identity`, so Ash has no record of it and
    # would otherwise create a second, functionally-identical index here.
    # Drop the old one and replace it with the Ash-managed, explicitly named
    # index backing the new `unique_idempotency_key` identity.
    drop_if_exists index(:agent_runs, [:idempotency_key],
                     name: "agent_runs_idempotency_key_index"
                   )

    create unique_index(:agent_runs, [:idempotency_key],
             name: "agent_runs_unique_idempotency_key_index",
             where: "(idempotency_key IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_runs, [:idempotency_key],
                     name: "agent_runs_unique_idempotency_key_index"
                   )

    create unique_index(:agent_runs, [:idempotency_key],
             name: "agent_runs_idempotency_key_index",
             where: "idempotency_key IS NOT NULL"
           )
  end
end
