defmodule Magus.Repo.Migrations.AddSkillTrusts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skill_trusts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :bundle_sha_at_grant, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "skill_trusts_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :skill_id,
          references(:skills,
            column: :id,
            name: "skill_trusts_skill_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:skill_trusts, [:user_id, :skill_id],
             name: "skill_trusts_unique_user_skill_index"
           )
  end

  def down do
    drop constraint(:skill_trusts, "skill_trusts_user_id_fkey")

    drop constraint(:skill_trusts, "skill_trusts_skill_id_fkey")

    drop_if_exists unique_index(:skill_trusts, [:user_id, :skill_id],
                     name: "skill_trusts_unique_user_skill_index"
                   )

    drop table(:skill_trusts)
  end
end
