defmodule Magus.Repo.Migrations.AddThreadFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :is_thread, :boolean, null: false, default: false
      add :branched_at, :utc_datetime_usec

      add :branched_at_message_id,
          references(:messages,
            column: :id,
            name: "conversations_branched_at_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:conversations, [:parent_conversation_id],
             where: "is_thread = true",
             name: "conversations_thread_parent_idx"
           )
  end

  def down do
    drop_if_exists index(:conversations, [:parent_conversation_id],
                     name: "conversations_thread_parent_idx"
                   )

    drop constraint(:conversations, "conversations_branched_at_message_id_fkey")

    alter table(:conversations) do
      remove :branched_at_message_id
      remove :branched_at
      remove :is_thread
    end
  end
end
