defmodule Magus.Repo.Migrations.AddCustomAgentToBrains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brains) do
      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "brains_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:brains, "brains_custom_agent_id_fkey")

    alter table(:brains) do
      remove :custom_agent_id
    end
  end
end
