defmodule Magus.Repo.Migrations.AddLastAccessedAtAndConsolidationTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :last_memory_consolidation_at, :utc_datetime_usec
    end

    alter table(:memories) do
      add :last_accessed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:memories) do
      remove :last_accessed_at
    end

    alter table(:conversations) do
      remove :last_memory_consolidation_at
    end
  end
end
