defmodule Magus.Repo.Migrations.StripeProductIdAndPriceCache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:platform_pricing) do
      add :stripe_product_id, :text
    end

    alter table(:pricing_tiers) do
      modify :annual_price_cents, :bigint, null: true
      modify :monthly_price_cents, :bigint, null: true
    end
  end

  def down do
    alter table(:pricing_tiers) do
      modify :monthly_price_cents, :bigint, null: false
      modify :annual_price_cents, :bigint, null: false
    end

    alter table(:platform_pricing) do
      remove :stripe_product_id
    end
  end
end
