defmodule Magus.Repo.Migrations.DropConversationApprovedSkillIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      remove :approved_skill_ids
    end
  end

  def down do
    alter table(:conversations) do
      add :approved_skill_ids, {:array, :uuid}, default: []
    end
  end
end
