defmodule Magus.Repo.Migrations.ScopeCustomAgentHandlePerWorkspace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:custom_agents, [:handle, :user_id],
                     name: "custom_agents_unique_handle_per_user_index"
                   )

    create unique_index(:custom_agents, [:handle, :workspace_id],
             name: "custom_agents_unique_handle_per_workspace_index",
             where: "(workspace_id IS NOT NULL) AND (deleted_at IS NULL)"
           )

    create unique_index(:custom_agents, [:handle, :user_id],
             name: "custom_agents_unique_handle_personal_index",
             where: "(workspace_id IS NULL) AND (deleted_at IS NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:custom_agents, [:handle, :user_id],
                     name: "custom_agents_unique_handle_personal_index"
                   )

    drop_if_exists unique_index(:custom_agents, [:handle, :workspace_id],
                     name: "custom_agents_unique_handle_per_workspace_index"
                   )

    create unique_index(:custom_agents, [:handle, :user_id],
             where: "(deleted_at IS NULL)",
             name: "custom_agents_unique_handle_per_user_index"
           )
  end
end
