defmodule Magus.Repo.Migrations.AddTaskConversationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :is_task_conversation, :boolean, null: false, default: false

      add :parent_conversation_id,
          references(:conversations,
            column: :id,
            name: "conversations_parent_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_parent_conversation_id_fkey")

    alter table(:conversations) do
      remove :parent_conversation_id
      remove :is_task_conversation
    end
  end
end
