defmodule Magus.Repo.Migrations.AddStripePaygProductId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:platform_pricing) do
      add :stripe_payg_product_id, :text
    end
  end

  def down do
    alter table(:platform_pricing) do
      remove :stripe_payg_product_id
    end
  end
end
