defmodule Magus.Repo.Migrations.AddRoutingSlotsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Seed routing_slots from existing model data before removing columns
    # (only relevant for dev DBs where the old undeployed migration was applied)
    create table(:routing_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :specialty, :text, null: false
      add :tier, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :model_id,
          references(:models,
            column: :id,
            name: "routing_slots_model_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:routing_slots, [:specialty, :tier],
             name: "routing_slots_unique_slot_index"
           )

    # Migrate existing routing data from models table (dev DBs only)
    execute """
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'models' AND column_name = 'routing_enabled?'
      ) THEN
        INSERT INTO routing_slots (id, model_id, specialty, tier, inserted_at, updated_at)
        SELECT gen_random_uuid(), id, routing_specialty, routing_tier, now(), now()
        FROM models
        WHERE "routing_enabled?" = true
          AND routing_specialty IS NOT NULL
          AND routing_tier IS NOT NULL;
      END IF;
    END $$;
    """

    # Remove old routing columns from models (dev DBs only)
    execute """
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'models' AND column_name = 'routing_enabled?'
      ) THEN
        ALTER TABLE models
          DROP COLUMN "routing_enabled?",
          DROP COLUMN routing_specialty,
          DROP COLUMN routing_tier;
      END IF;
    END $$;
    """
  end

  def down do
    drop_if_exists unique_index(:routing_slots, [:specialty, :tier],
                     name: "routing_slots_unique_slot_index"
                   )

    drop constraint(:routing_slots, "routing_slots_model_id_fkey")

    drop table(:routing_slots)
  end
end
