defmodule Magus.Repo.Migrations.ProviderKeyMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Step 1: Add provider_key column (nullable initially for backfill)
    alter table(:user_integrations) do
      add :provider_key, :text
    end

    # Step 2: Backfill provider_key from the provider relationship
    execute """
      UPDATE user_integrations
      SET provider_key = (SELECT key FROM integration_providers WHERE id = user_integrations.provider_id)::text
      WHERE provider_id IS NOT NULL
    """

    # Step 3: Make provider_key NOT NULL after backfill
    alter table(:user_integrations) do
      modify :provider_key, :text, null: false
    end

    # Step 4: Drop provider_id column
    alter table(:user_integrations) do
      remove :provider_id
    end

    # Step 5: Update unique index
    drop_if_exists unique_index(:user_integrations, [:custom_agent_id, :provider_id],
                     name: "user_integrations_unique_agent_provider_index"
                   )

    create unique_index(:user_integrations, [:custom_agent_id, :provider_key],
             name: "user_integrations_unique_agent_provider_index"
           )

    # Step 6: Drop the integration_providers table (no longer needed)
    drop table(:integration_providers)
  end

  def down do
    # Recreate integration_providers table
    create table(:integration_providers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :auth_type, :text, null: false
      add :supports_input?, :boolean, default: false
      add :supports_output?, :boolean, default: false
      add :operations, {:array, :text}, default: []
      add :config_schema, :map, default: %{}
      add :is_active, :boolean, default: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:integration_providers, [:key],
             name: "integration_providers_unique_key_index"
           )

    drop_if_exists unique_index(:user_integrations, [:custom_agent_id, :provider_key],
                     name: "user_integrations_unique_agent_provider_index"
                   )

    alter table(:user_integrations) do
      remove :provider_key

      add :provider_id,
          references(:integration_providers,
            column: :id,
            name: "user_integrations_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_integrations, [:custom_agent_id, :provider_id],
             name: "user_integrations_unique_agent_provider_index"
           )
  end
end
