defmodule Magus.Repo.Migrations.AddBrainPagesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:brain_pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :position, :float, null: false
      add :icon, :text
      add :contributor_type, :text
      add :contributor_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brain_id,
          references(:brains,
            column: :id,
            name: "brain_pages_brain_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:brain_pages, [:brain_id, :slug],
             name: "brain_pages_unique_slug_per_brain_index"
           )
  end

  def down do
    drop_if_exists unique_index(:brain_pages, [:brain_id, :slug],
                     name: "brain_pages_unique_slug_per_brain_index"
                   )

    drop constraint(:brain_pages, "brain_pages_brain_id_fkey")

    drop table(:brain_pages)
  end
end
