defmodule Magus.Repo.Migrations.AddUserModelPreferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_model_preferences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :favorite?, :boolean, null: false, default: false
      add :hidden?, :boolean, null: false, default: false
      add :position, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_model_preferences_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :model_id,
          references(:models,
            column: :id,
            name: "user_model_preferences_model_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:user_model_preferences, [:user_id, :model_id],
             name: "user_model_preferences_unique_user_model_index"
           )
  end

  def down do
    drop constraint(:user_model_preferences, "user_model_preferences_user_id_fkey")

    drop constraint(:user_model_preferences, "user_model_preferences_model_id_fkey")

    drop_if_exists unique_index(:user_model_preferences, [:user_id, :model_id],
                     name: "user_model_preferences_unique_user_model_index"
                   )

    drop table(:user_model_preferences)
  end
end
