defmodule Magus.Repo.Migrations.AddSyncLogToKnowledgeCollections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_collections) do
      add :sync_log, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:knowledge_collections) do
      remove :sync_log
    end
  end
end
