defmodule Magus.Repo.Migrations.SkillFavoritesOnDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:skill_favorites, "skill_favorites_skill_id_fkey")

    drop constraint(:skill_favorites, "skill_favorites_user_id_fkey")

    alter table(:skill_favorites) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "skill_favorites_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :skill_id,
             references(:skills,
               column: :id,
               name: "skill_favorites_skill_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:skill_favorites, "skill_favorites_user_id_fkey")

    drop constraint(:skill_favorites, "skill_favorites_skill_id_fkey")

    alter table(:skill_favorites) do
      modify :skill_id,
             references(:skills,
               column: :id,
               name: "skill_favorites_skill_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "skill_favorites_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
