defmodule Magus.Repo.Migrations.CreateConversationShareLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversation_share_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :token, :text, null: false
      add :access_type, :text, null: false, default: "public"
      add :label, :text
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_share_links_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "conversation_share_links_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:conversation_share_links, [:token],
             name: "conversation_share_links_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:conversation_share_links, [:token],
                     name: "conversation_share_links_unique_token_index"
                   )

    drop constraint(:conversation_share_links, "conversation_share_links_conversation_id_fkey")

    drop constraint(:conversation_share_links, "conversation_share_links_created_by_id_fkey")

    drop table(:conversation_share_links)
  end
end
