defmodule Magus.Repo.Migrations.AddMemoryProfileSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_profile_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :document, :text, null: false, default: ""
      add :token_estimate, :bigint, null: false, default: 0
      add :changed_by, :text, default: "system"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_profile_id, :uuid, null: false
    end

    alter table(:conversations) do
      add :last_extracted_message_at, :utc_datetime_usec
    end

    create table(:user_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_profile_versions) do
      modify :user_profile_id,
             references(:user_profiles,
               column: :id,
               name: "user_profile_versions_user_profile_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:user_profiles) do
      add :document, :text, null: false, default: ""
      add :pending_notes, {:array, :text}, null: false, default: []
      add :token_estimate, :bigint, null: false, default: 0
      add :last_distilled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "user_profiles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:user_profiles, [:user_id, :workspace_id],
             name: "user_profiles_unique_bucket_index",
             nulls_distinct: false
           )

    alter table(:users) do
      add :profile_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :profile_enabled
    end

    drop constraint(:user_profiles, "user_profiles_user_id_fkey")

    drop constraint(:user_profiles, "user_profiles_workspace_id_fkey")

    drop_if_exists unique_index(:user_profiles, [:user_id, :workspace_id],
                     name: "user_profiles_unique_bucket_index"
                   )

    alter table(:user_profiles) do
      remove :workspace_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :last_distilled_at
      remove :token_estimate
      remove :pending_notes
      remove :document
    end

    drop constraint(:user_profile_versions, "user_profile_versions_user_profile_id_fkey")

    alter table(:user_profile_versions) do
      modify :user_profile_id, :uuid
    end

    drop table(:user_profiles)

    alter table(:conversations) do
      remove :last_extracted_message_at
    end

    drop table(:user_profile_versions)
  end
end
