defmodule Magus.Repo.Migrations.CreateCustomAgentAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:custom_agent_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mode, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "custom_agent_attachments_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :file_id,
          references(:files,
            column: :id,
            name: "custom_agent_attachments_file_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:custom_agent_attachments, [:custom_agent_id, :file_id],
             name: "custom_agent_attachments_unique_agent_file_index"
           )
  end

  def down do
    drop_if_exists unique_index(:custom_agent_attachments, [:custom_agent_id, :file_id],
                     name: "custom_agent_attachments_unique_agent_file_index"
                   )

    drop constraint(:custom_agent_attachments, "custom_agent_attachments_custom_agent_id_fkey")

    drop constraint(:custom_agent_attachments, "custom_agent_attachments_file_id_fkey")

    drop table(:custom_agent_attachments)
  end
end
