defmodule Magus.Repo.Migrations.AddKnowledgeSourceNeedsReauth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_sources) do
      add :needs_reauth, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:knowledge_sources) do
      remove :needs_reauth
    end
  end
end
