defmodule Magus.Repo.Migrations.CreateMcpServers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mcp_servers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :handle, :text, null: false
      add :url, :text, null: false
      add :transport, :text, null: false, default: "streamable_http"
      add :mcp_path, :text, null: false, default: "/mcp"
      add :enabled?, :boolean, null: false, default: true
      add :auth_type, :text, null: false, default: "none"
      add :cached_tools, {:array, :map}, null: false, default: []
      add :tools_cached_at, :utc_datetime_usec
      add :oauth_metadata, :map, null: false, default: %{}
      add :reachability, :text, null: false, default: "unknown"
      add :last_error, :text
      add :last_reachable_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "mcp_servers_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "mcp_servers_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:mcp_servers, [:workspace_id, :handle],
             name: "mcp_servers_unique_handle_per_workspace_index",
             where: "(workspace_id IS NOT NULL)"
           )

    create unique_index(:mcp_servers, [:user_id, :handle],
             name: "mcp_servers_unique_handle_personal_index",
             where: "(workspace_id IS NULL)"
           )
  end

  def down do
    drop constraint(:mcp_servers, "mcp_servers_user_id_fkey")

    drop constraint(:mcp_servers, "mcp_servers_workspace_id_fkey")

    drop_if_exists unique_index(:mcp_servers, [:user_id, :handle],
                     name: "mcp_servers_unique_handle_personal_index"
                   )

    drop_if_exists unique_index(:mcp_servers, [:workspace_id, :handle],
                     name: "mcp_servers_unique_handle_per_workspace_index"
                   )

    drop table(:mcp_servers)
  end
end
