defmodule Magus.Repo.Migrations.FixSyncCursorType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    ALTER TABLE knowledge_collections
    ALTER COLUMN sync_cursor TYPE jsonb
    USING CASE
      WHEN sync_cursor IS NOT NULL THEN jsonb_build_object('sync_cursor', sync_cursor)
      ELSE '{}'::jsonb
    END,
    ALTER COLUMN sync_cursor SET DEFAULT '{}'::jsonb
    """
  end

  def down do
    alter table(:knowledge_collections) do
      modify :sync_cursor, :text, default: nil
    end
  end
end
