defmodule Magus.Repo.Migrations.AddVideoGenerationSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :video_generation_settings, :map
    end

    alter table(:users) do
      add :video_generation_settings, :map
    end
  end

  def down do
    alter table(:users) do
      remove :video_generation_settings
    end

    alter table(:conversations) do
      remove :video_generation_settings
    end
  end
end
