defmodule Magus.Repo.Migrations.AddOrgHardeningIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:workspaces, [:organization_id])

    create index(:organization_members, [:user_id])
  end

  def down do
    drop_if_exists index(:organization_members, [:user_id])

    drop_if_exists index(:workspaces, [:organization_id])
  end
end
