defmodule Magus.Repo.Migrations.AddFileBaseFilter do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:files, [:knowledge_collection_id, :external_id],
                     name: "files_unique_collection_external_index"
                   )

    create unique_index(:files, [:knowledge_collection_id, :external_id],
             name: "files_unique_collection_external_index",
             where: "(knowledge_collection_id IS NOT NULL) AND (deleted_at IS NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:files, [:knowledge_collection_id, :external_id],
                     name: "files_unique_collection_external_index"
                   )

    create unique_index(:files, [:knowledge_collection_id, :external_id],
             name: "files_unique_collection_external_index",
             where: "(knowledge_collection_id IS NOT NULL)"
           )
  end
end
