defmodule Magus.Repo.Migrations.AddPricingTiers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_plans) do
      add :daily_basic_messages, :bigint
      add :daily_standard_messages, :bigint
    end

    alter table(:models) do
      add :pricing_tier, :text, null: false, default: "standard"
    end

    # Data migration: set pricing_tier based on output_cost_value
    # basic: output ≤ $5/M, standard: output ≤ $15/M, premium: output > $15/M
    execute("""
    UPDATE models SET pricing_tier = 'basic'
    WHERE output_cost_value IS NOT NULL AND output_cost_value <= 5
    AND output_cost_unit = 'per_million_tokens'
    """)

    execute("""
    UPDATE models SET pricing_tier = 'premium'
    WHERE output_cost_value IS NOT NULL AND output_cost_value > 15
    AND output_cost_unit = 'per_million_tokens'
    """)

    alter table(:user_usage_overrides) do
      add :bonus_daily_basic_messages, :bigint, default: 0
      add :bonus_daily_standard_messages, :bigint, default: 0
    end
  end

  def down do
    alter table(:user_usage_overrides) do
      remove :bonus_daily_standard_messages
      remove :bonus_daily_basic_messages
    end

    alter table(:models) do
      remove :pricing_tier
    end

    alter table(:usage_plans) do
      remove :daily_standard_messages
      remove :daily_basic_messages
    end
  end
end
