defmodule Magus.Repo.Migrations.AddTimezoneRateLimit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :last_timezone_change_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :last_timezone_change_at
    end
  end
end
