defmodule Magus.Repo.Migrations.SimplifyPrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false

      add :version_source_id,
          references(:prompts,
            column: :id,
            name: "prompts_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "prompts_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:prompts) do
      remove :estimated_tokens
      remove :version
      add :additional_information, :text
    end

    drop_if_exists table(:prompt_examples)
  end

  def down do
    alter table(:prompts) do
      remove :additional_information
      add :version, :text, default: "1.0"
      add :estimated_tokens, :text
    end

    drop constraint(:prompts_versions, "prompts_versions_version_source_id_fkey")

    drop constraint(:prompts_versions, "prompts_versions_user_id_fkey")

    drop table(:prompts_versions)
  end
end
