defmodule Magus.Repo.Migrations.AddOpenRouterProviders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:open_router_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :headquarters, :text
      add :datacenters, {:array, :text}, null: false, default: []
      add :privacy_policy_url, :text
      add :terms_of_service_url, :text
      add :status_page_url, :text
      add :allowed, :boolean, null: false, default: false
      add :last_synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:open_router_providers, [:slug], name: "open_router_providers_slug_index")
  end

  def down do
    drop_if_exists unique_index(:open_router_providers, [:slug],
                     name: "open_router_providers_slug_index"
                   )

    drop table(:open_router_providers)
  end
end
