defmodule Magus.Repo.Migrations.SpawnRecurrence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memories) do
      add :structured_data, :map
    end
  end

  def down do
    alter table(:memories) do
      remove :structured_data
    end
  end
end
