defmodule Magus.Repo.Migrations.AddAgentIsolationFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :can_read_global_memories, :boolean, default: true
      add :can_write_global_memories, :boolean, default: true
      add :can_access_global_files, :boolean, default: true
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :can_access_global_files
      remove :can_write_global_memories
      remove :can_read_global_memories
    end
  end
end
