defmodule Magus.Repo.Migrations.TightenAgentRunEventFkNilify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:agent_runs, "agent_runs_event_id_fkey")

    alter table(:agent_runs) do
      modify :event_id,
             references(:agent_inbox_events,
               column: :id,
               name: "agent_runs_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:agent_runs, "agent_runs_event_id_fkey")

    alter table(:agent_runs) do
      modify :event_id,
             references(:agent_inbox_events,
               column: :id,
               name: "agent_runs_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
