defmodule Magus.Repo.Migrations.AddCredentialExpiryWarned do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:integration_credentials) do
      add :expiry_warned_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:integration_credentials) do
      remove :expiry_warned_at
    end
  end
end
