defmodule Magus.Repo.Migrations.SuperBrainEpisodeMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:super_brain_episodes) do
      add :metadata, :map
    end
  end

  def down do
    alter table(:super_brain_episodes) do
      remove :metadata
    end
  end
end
