defmodule Magus.Repo.Migrations.RenameReplyEnabledToAsyncReplyEnabled do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:user_integrations), :reply_enabled, to: :async_reply_enabled
  end

  def down do
    rename table(:user_integrations), :async_reply_enabled, to: :reply_enabled
  end
end
