defmodule Magus.Repo.Migrations.CollapsePageKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      remove :spec_page_id
      remove :delivery_ref
      remove :delivered_at
    end
  end

  def down do
    alter table(:brain_pages) do
      add :delivered_at, :utc_datetime_usec
      add :delivery_ref, :text

      add :spec_page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_pages_spec_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end
end
