defmodule Magus.Repo.Migrations.DropSuperBrainEpisodesFullUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:super_brain_episodes, [:resource_type, :resource_id],
                     name: "super_brain_episodes_unique_resource_index"
                   )
  end

  def down do
    create unique_index(:super_brain_episodes, [:resource_type, :resource_id],
             name: "super_brain_episodes_unique_resource_index"
           )
  end
end
