defmodule Magus.Repo.Migrations.IntegrationConversationCleanup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:integration_conversations, "integration_conversations_conversation_id_fkey")

    drop constraint(
           :integration_conversations,
           "integration_conversations_user_integration_id_fkey"
         )

    alter table(:integration_conversations) do
      modify :user_integration_id,
             references(:user_integrations,
               column: :id,
               name: "integration_conversations_user_integration_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "integration_conversations_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(
           :integration_conversations,
           "integration_conversations_user_integration_id_fkey"
         )

    drop constraint(:integration_conversations, "integration_conversations_conversation_id_fkey")

    alter table(:integration_conversations) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "integration_conversations_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_integration_id,
             references(:user_integrations,
               column: :id,
               name: "integration_conversations_user_integration_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
