defmodule Magus.Repo.Migrations.AddDeliveredToParentAtToAgentRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_runs) do
      add :delivered_to_parent_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:agent_runs) do
      remove :delivered_to_parent_at
    end
  end
end
