defmodule Magus.Repo.Migrations.UpdateWorkspaceMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspace_members) do
      modify :user_id, :uuid, null: true
      add :status, :text, null: false, default: "invited"
      add :invited_at, :utc_datetime_usec
      add :joined_at, :utc_datetime_usec
      add :deactivated_at, :utc_datetime_usec
      add :invite_token, :text
      add :invite_email, :text
    end

    create unique_index(:workspace_members, [:workspace_id, :invite_email],
             name: "workspace_members_unique_invite_index"
           )

    create unique_index(:workspace_members, [:workspace_id, :user_id],
             name: "workspace_members_unique_membership_index",
             where: "(user_id IS NOT NULL)"
           )

    create unique_index(:workspace_members, [:invite_token],
             name: "workspace_members_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workspace_members, [:invite_token],
                     name: "workspace_members_unique_token_index"
                   )

    drop_if_exists unique_index(:workspace_members, [:workspace_id, :user_id],
                     name: "workspace_members_unique_membership_index"
                   )

    drop_if_exists unique_index(:workspace_members, [:workspace_id, :invite_email],
                     name: "workspace_members_unique_invite_index"
                   )

    alter table(:workspace_members) do
      remove :invite_email
      remove :invite_token
      remove :deactivated_at
      remove :joined_at
      remove :invited_at
      remove :status
      modify :user_id, :uuid, null: false
    end
  end
end
