defmodule Magus.Repo.Migrations.AddCustomAgentAutonomyFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :is_paused, :boolean, default: false
      add :max_daily_runs, :bigint
      add :max_tokens_per_run, :bigint
      add :heartbeat_enabled, :boolean, default: false
      add :heartbeat_instructions, :text
      add :heartbeat_default_interval_minutes, :bigint, default: 360
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :heartbeat_default_interval_minutes
      remove :heartbeat_instructions
      remove :heartbeat_enabled
      remove :max_tokens_per_run
      remove :max_daily_runs
      remove :is_paused
    end
  end
end
