defmodule Magus.Repo.Migrations.AddOrganizationMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organization_members_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:organization_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:organization_members_versions) do
      modify :version_source_id,
             references(:organization_members,
               column: :id,
               name: "organization_members_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "organization_members_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:organization_members) do
      add :role, :text, null: false, default: "member"
      add :status, :text, null: false, default: "invited"
      add :spend_cap_cents, :bigint
      add :invited_at, :utc_datetime_usec
      add :joined_at, :utc_datetime_usec
      add :removed_at, :utc_datetime_usec
      add :invite_token, :text
      add :invite_expires_at, :utc_datetime_usec
      add :invite_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_members_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "organization_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:organization_members, [:organization_id, :invite_email],
             name: "organization_members_unique_invite_index",
             where: "(status != 'removed')"
           )

    create unique_index(:organization_members, [:organization_id, :user_id],
             name: "organization_members_unique_membership_index",
             where: "(user_id IS NOT NULL)"
           )

    create unique_index(:organization_members, [:invite_token],
             name: "organization_members_unique_token_index"
           )
  end

  def down do
    drop constraint(:organization_members, "organization_members_organization_id_fkey")

    drop constraint(:organization_members, "organization_members_user_id_fkey")

    drop_if_exists unique_index(:organization_members, [:invite_token],
                     name: "organization_members_unique_token_index"
                   )

    drop_if_exists unique_index(:organization_members, [:organization_id, :user_id],
                     name: "organization_members_unique_membership_index"
                   )

    drop_if_exists unique_index(:organization_members, [:organization_id, :invite_email],
                     name: "organization_members_unique_invite_index"
                   )

    alter table(:organization_members) do
      remove :user_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :invite_email
      remove :invite_expires_at
      remove :invite_token
      remove :removed_at
      remove :joined_at
      remove :invited_at
      remove :spend_cap_cents
      remove :status
      remove :role
    end

    drop constraint(
           :organization_members_versions,
           "organization_members_versions_version_source_id_fkey"
         )

    drop constraint(:organization_members_versions, "organization_members_versions_user_id_fkey")

    alter table(:organization_members_versions) do
      modify :user_id, :uuid
      modify :version_source_id, :uuid
    end

    drop table(:organization_members)

    drop table(:organization_members_versions)
  end
end
