defmodule Magus.Repo.Migrations.AddWorkspaceToSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_subscriptions) do
      add :managed_by_workspace, :boolean, null: false, default: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "user_subscriptions_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:user_subscriptions, [:user_id],
                     name: "user_subscriptions_unique_user_index"
                   )

    create unique_index(:user_subscriptions, [:user_id],
             name: "user_subscriptions_unique_user_personal_index",
             where: "(workspace_id IS NULL)"
           )

    create unique_index(:user_subscriptions, [:user_id, :workspace_id],
             name: "user_subscriptions_unique_user_workspace_index",
             where: "(workspace_id IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:user_subscriptions, [:user_id, :workspace_id],
                     name: "user_subscriptions_unique_user_workspace_index"
                   )

    drop_if_exists unique_index(:user_subscriptions, [:user_id],
                     name: "user_subscriptions_unique_user_personal_index"
                   )

    create unique_index(:user_subscriptions, [:user_id],
             name: "user_subscriptions_unique_user_index"
           )

    drop constraint(:user_subscriptions, "user_subscriptions_workspace_id_fkey")

    alter table(:user_subscriptions) do
      remove :workspace_id
      remove :managed_by_workspace
    end
  end
end
