defmodule Magus.Repo.Migrations.AddSkillContextToConversation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :skill_context, :text
    end
  end

  def down do
    alter table(:conversations) do
      remove :skill_context
    end
  end
end
