defmodule Magus.Repo.Migrations.AddMemorySourcesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memory_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :source_type, :text, null: false
      add :source_uri, :text
      add :title, :text
      add :context_snippet, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :memory_id,
          references(:memories,
            column: :id,
            name: "memory_sources_memory_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:memory_sources, "memory_sources_memory_id_fkey")

    drop table(:memory_sources)
  end
end
