defmodule Magus.Repo.Migrations.AddSuperBrainClaims do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:super_brain_claims, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :graph_name, :text, null: false

      add :episode_id,
          references(:super_brain_episodes,
            column: :id,
            name: "super_brain_claims_episode_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :source_user_id, :uuid, null: false
      add :subject_name, :text, null: false
      add :subject_type, :text
      add :subject_key, :text, null: false
      add :object_name, :text, null: false
      add :object_type, :text
      add :object_key, :text, null: false
      add :predicate, :text, null: false
      add :polarity, :text, null: false, default: "affirms"
      add :claim_text, :text, null: false
      add :confidence, :float
      add :trust_tier, :text, null: false, default: "evidence"
      add :asserted_at, :utc_datetime
      add :valid_from, :utc_datetime
      add :valid_to, :utc_datetime
      add :embedding, :vector

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:super_brain_claims, [:graph_name])
    create index(:super_brain_claims, [:subject_key])
    create index(:super_brain_claims, [:object_key])
    create index(:super_brain_claims, [:episode_id])
    create index(:super_brain_claims, [:source_user_id])

    # pgvector: size the embedding column and add an HNSW cosine index,
    # mirroring file_chunks (Ash cannot express either through the snapshot).
    execute "ALTER TABLE super_brain_claims ALTER COLUMN embedding TYPE vector(1536)"

    execute """
    CREATE INDEX super_brain_claims_embedding_idx ON super_brain_claims
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64)
    """
  end

  def down do
    execute "DROP INDEX IF EXISTS super_brain_claims_embedding_idx"

    drop constraint(:super_brain_claims, "super_brain_claims_episode_id_fkey")

    drop table(:super_brain_claims)
  end
end
