defmodule Magus.Repo.Migrations.AddExecutionTypeAndCommand do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sandbox_executions) do
      add :type, :text, null: false, default: "python_code"
      add :command, :text
    end
  end

  def down do
    alter table(:sandbox_executions) do
      remove :command
      remove :type
    end
  end
end
