defmodule Magus.Repo.Migrations.AddBrainBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:brain_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :type, :text, null: false
      add :content, :map, default: %{}
      add :position, :float, null: false
      add :depth, :bigint, default: 0
      add :metadata, :map, default: %{}
      add :is_pinned, :boolean, default: false
      add :contributor_type, :text
      add :contributor_id, :uuid
      add :embedding, :vector
      add :lock_version, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_blocks_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :parent_block_id,
          references(:brain_blocks,
            column: :id,
            name: "brain_blocks_parent_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:brain_blocks, "brain_blocks_page_id_fkey")

    drop constraint(:brain_blocks, "brain_blocks_parent_block_id_fkey")

    drop table(:brain_blocks)
  end
end
