defmodule Magus.Repo.Migrations.AddSkillFavorites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skill_favorites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "skill_favorites_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :skill_id,
          references(:skills,
            column: :id,
            name: "skill_favorites_skill_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:skill_favorites, [:user_id, :skill_id],
             name: "skill_favorites_unique_user_skill_favorite_index"
           )
  end

  def down do
    drop constraint(:skill_favorites, "skill_favorites_user_id_fkey")

    drop constraint(:skill_favorites, "skill_favorites_skill_id_fkey")

    drop_if_exists unique_index(:skill_favorites, [:user_id, :skill_id],
                     name: "skill_favorites_unique_user_skill_favorite_index"
                   )

    drop table(:skill_favorites)
  end
end
