defmodule Magus.Repo.Migrations.AddUserProfileEnabled do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :profile_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :profile_enabled
    end
  end
end
