defmodule Magus.Repo.Migrations.UpdateInterestProfileEmbeddingType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:curation_interest_profiles) do
      modify :embedding, :vector
    end
  end

  def down do
    alter table(:curation_interest_profiles) do
      modify :embedding, :vector, size: 1536
    end
  end
end
