defmodule Magus.Repo.Migrations.AddServiceConfigToSandbox do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sandboxes) do
      add :service_config, :map
    end
  end

  def down do
    alter table(:sandboxes) do
      remove :service_config
    end
  end
end
