defmodule Magus.Repo.Migrations.AddWorkspaceIdToBrains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brains) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "brains_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:brains, "brains_workspace_id_fkey")

    alter table(:brains) do
      remove :workspace_id
    end
  end
end
