defmodule Magus.Repo.Migrations.DropUserDataRegionColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :data_region_consents
      remove :data_region_preference
    end
  end

  def down do
    # Restore the ORIGINAL default (see 20260314125510): the old region code
    # treats an empty preference list as "no regions allowed", so a rollback
    # with default [] would block every OpenRouter model for every user.
    alter table(:users) do
      add :data_region_preference, {:array, :text},
        null: false,
        default: fragment("ARRAY['US', 'EU', 'CH']::text[]")

      add :data_region_consents, :map, null: false, default: %{}
    end
  end
end
