defmodule Magus.Repo.Migrations.AddTaskAndEventToAgentRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_runs) do
      add :task_id, :uuid

      add :event_id,
          references(:agent_inbox_events,
            column: :id,
            name: "agent_runs_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:agent_runs, "agent_runs_event_id_fkey")

    alter table(:agent_runs) do
      remove :event_id
      remove :task_id
    end
  end
end
