defmodule Magus.Repo.Migrations.RemoveVersionFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:prompts_versions, "prompts_versions_version_source_id_fkey")

    alter table(:prompts_versions) do
      modify :version_source_id, :uuid
    end

    create index(:prompts_versions, [:version_source_id])
  end

  def down do
    drop_if_exists index(:prompts_versions, [:version_source_id])

    alter table(:prompts_versions) do
      modify :version_source_id,
             references(:prompts,
               column: :id,
               name: "prompts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
