defmodule Magus.Repo.Migrations.AddSuperGraphMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:super_brain_super_graphs) do
      add :metrics, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:super_brain_super_graphs) do
      remove :metrics
    end
  end
end
