defmodule Magus.Repo.Migrations.AddCanAccessKnowledgeToCustomAgent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :can_access_knowledge, :boolean, default: true
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :can_access_knowledge
    end
  end
end
