defmodule Magus.Repo.Migrations.AddTagScoping do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add :user_id,
          references(:users,
            column: :id,
            name: "tags_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "tags_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    drop_if_exists unique_index(:tags, [:name], name: "tags_unique_name_index")
    # The original create_tags migration used Ecto's default index name.
    drop_if_exists unique_index(:tags, [:name], name: "tags_name_index")

    create unique_index(:tags, [:name, :user_id, :workspace_id],
             name: "tags_unique_name_per_scope_index",
             nulls_distinct: false
           )

    create index(:tags, [:user_id])

    create index(:tags, [:workspace_id])
  end

  def down do
    drop_if_exists index(:tags, [:workspace_id])

    drop_if_exists index(:tags, [:user_id])

    drop constraint(:tags, "tags_user_id_fkey")

    drop constraint(:tags, "tags_workspace_id_fkey")

    drop_if_exists unique_index(:tags, [:name, :user_id, :workspace_id],
                     name: "tags_unique_name_per_scope_index"
                   )

    create unique_index(:tags, [:name])

    alter table(:tags) do
      remove :workspace_id
      remove :user_id
    end
  end
end
