defmodule Magus.Repo.Migrations.AddDeletedAtToBrainPages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      add :deleted_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:brain_pages, [:brain_id, :slug],
                     name: "brain_pages_unique_slug_per_brain_index"
                   )

    create unique_index(:brain_pages, [:brain_id, :slug],
             name: "brain_pages_unique_slug_per_brain_index",
             where: "(deleted_at IS NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:brain_pages, [:brain_id, :slug],
                     name: "brain_pages_unique_slug_per_brain_index"
                   )

    create unique_index(:brain_pages, [:brain_id, :slug],
             name: "brain_pages_unique_slug_per_brain_index"
           )

    alter table(:brain_pages) do
      remove :deleted_at
    end
  end
end
