defmodule Magus.Repo.Migrations.AddSpecKindAndLink do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      add :spec_page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_pages_spec_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:brain_pages, "brain_pages_spec_page_id_fkey")

    alter table(:brain_pages) do
      remove :spec_page_id
    end
  end
end
