defmodule Magus.Repo.Migrations.AddAccountSponsorOrgId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_subscriptions) do
      add :sponsor_org_id,
          references(:organizations,
            column: :id,
            name: "user_subscriptions_sponsor_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:user_subscriptions, "user_subscriptions_sponsor_org_id_fkey")

    alter table(:user_subscriptions) do
      remove :sponsor_org_id
    end
  end
end
