defmodule Magus.Repo.Migrations.RemoveExtractionDenormalizedFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:conversations, [:last_message_at],
                     name: "conversations_needing_extraction_idx"
                   )

    alter table(:conversations) do
      remove :last_message_at
      remove :messages_since_extraction
    end
  end

  def down do
    alter table(:conversations) do
      add :messages_since_extraction, :bigint, null: false, default: 0
      add :last_message_at, :utc_datetime_usec
    end

    create index(:conversations, [:last_message_at],
             name: "conversations_needing_extraction_idx",
             where: "messages_since_extraction > 0"
           )
  end
end
