defmodule Magus.Repo.Migrations.AddModelProviderLink do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :llm_metadata, :map, null: false, default: %{}

      add :model_provider_id,
          references(:model_providers,
            column: :id,
            name: "models_model_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:models, "models_model_provider_id_fkey")

    alter table(:models) do
      remove :model_provider_id
      remove :llm_metadata
    end
  end
end
