defmodule Magus.Repo.Migrations.RemoveSponsoredSeats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # `seat_grants` backs the cloud-only `Magus.Billing.SeatGrant` resource, which
    # has no core resource, so codegen does not emit it. The sponsored-seats layer
    # is being removed, so drop the table here. Mirrors the `down` of the original
    # create migration (20260426195521_migrate_resources2). The `down` below
    # re-creates it faithfully. No production data exists for this table.
    drop_if_exists unique_index(:seat_grants, [:invite_token],
                     name: "seat_grants_unique_token_index"
                   )

    drop_if_exists unique_index(:seat_grants, [:sponsor_user_id, :recipient_email],
                     name: "seat_grants_unique_active_grant_index"
                   )

    drop_if_exists table(:seat_grants)

    alter table(:usage_plans) do
      remove :extra_seat_stripe_price_id
      remove :sponsorable_seats
    end

    alter table(:user_subscriptions) do
      remove :extra_seats
      remove :sponsor_user_id
    end

    drop_if_exists unique_index(:user_subscriptions, [:user_id],
                     name: "user_subscriptions_unique_user_personal_index"
                   )

    drop_if_exists unique_index(:user_subscriptions, [:user_id, :sponsor_user_id],
                     name: "user_subscriptions_unique_user_sponsor_index"
                   )

    create unique_index(:user_subscriptions, [:user_id],
             name: "user_subscriptions_unique_user_personal_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_subscriptions, [:user_id],
                     name: "user_subscriptions_unique_user_personal_index"
                   )

    # Columns must exist before the partial indexes below can reference them.
    alter table(:user_subscriptions) do
      add :sponsor_user_id,
          references(:users,
            column: :id,
            name: "user_subscriptions_sponsor_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :extra_seats, :bigint, null: false, default: 0
    end

    alter table(:usage_plans) do
      add :sponsorable_seats, :bigint
      add :extra_seat_stripe_price_id, :text
    end

    create unique_index(:user_subscriptions, [:user_id, :sponsor_user_id],
             name: "user_subscriptions_unique_user_sponsor_index",
             where: "(sponsor_user_id IS NOT NULL)"
           )

    create unique_index(:user_subscriptions, [:user_id],
             name: "user_subscriptions_unique_user_personal_index",
             where: "(sponsor_user_id IS NULL)"
           )

    # Faithful re-create of the `seat_grants` table, copied verbatim from the
    # `up` of the original create migration (20260426195521_migrate_resources2),
    # so this migration is fully reversible.
    create table(:seat_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :sponsor_user_id,
          references(:users,
            column: :id,
            name: "seat_grants_sponsor_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recipient_email, :citext, null: false

      add :recipient_user_id,
          references(:users,
            column: :id,
            name: "seat_grants_recipient_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :usage_plan_id,
          references(:usage_plans,
            column: :id,
            name: "seat_grants_usage_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :status, :text, null: false, default: "invited"
      add :invite_token, :text, null: false
      add :invite_expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:seat_grants, [:sponsor_user_id, :recipient_email],
             name: "seat_grants_unique_active_grant_index",
             where: "(status != 'revoked')"
           )

    create unique_index(:seat_grants, [:invite_token], name: "seat_grants_unique_token_index")
  end
end
