defmodule Magus.Repo.Migrations.AddUploadedViaAgentIdToFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :uploaded_via_agent_id,
          references(:custom_agents,
            column: :id,
            name: "files_uploaded_via_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:files, "files_uploaded_via_agent_id_fkey")

    alter table(:files) do
      remove :uploaded_via_agent_id
    end
  end
end
