defmodule Magus.Repo.Migrations.UpdateIdempotencyScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:agent_inbox_events, [:agent_id, :idempotency_key],
                     name: "agent_inbox_events_unique_idempotency_index"
                   )

    create unique_index(:agent_inbox_events, [:agent_id, :idempotency_key],
             name: "agent_inbox_events_unique_idempotency_index",
             where:
               "(idempotency_key IS NOT NULL AND status IN ('pending', 'waiting', 'processing'))"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_inbox_events, [:agent_id, :idempotency_key],
                     name: "agent_inbox_events_unique_idempotency_index"
                   )

    create unique_index(:agent_inbox_events, [:agent_id, :idempotency_key],
             name: "agent_inbox_events_unique_idempotency_index",
             where: "(idempotency_key IS NOT NULL)"
           )
  end
end
