defmodule Magus.Repo.Migrations.AddAgentInboxEventsAndActivityLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_activity_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :agent_id,
          references(:custom_agents,
            column: :id,
            name: "agent_activity_logs_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "agent_activity_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :activity_type, :text, null: false
      add :summary, :text, null: false
      add :event_id, :uuid
      add :run_id, :uuid
      add :task_id, :uuid
      add :conversation_id, :uuid
      add :details, :map, default: %{}
      add :model_used, :text
      add :tokens_used, :bigint
      add :estimated_cost_usd, :decimal
      add :duration_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:agent_inbox_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :agent_id,
          references(:custom_agents,
            column: :id,
            name: "agent_inbox_events_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "agent_inbox_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_type, :text, null: false
      add :urgency, :text, null: false, default: "deferred"
      add :status, :text, null: false, default: "pending"
      add :title, :text, null: false
      add :summary, :text
      add :payload, :map, default: %{}
      add :source_type, :text, null: false
      add :source_id, :text
      add :source_url, :text
      add :content_hash, :text
      add :idempotency_key, :text
      add :resolved_at, :utc_datetime_usec
      add :resolved_by, :text
      add :resolution_note, :text
      add :run_id, :uuid
      add :task_id, :uuid
      add :metadata, :map, default: %{}
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agent_inbox_events, [:agent_id, :content_hash],
             name: "agent_inbox_events_unique_content_hash_index",
             where: "(content_hash IS NOT NULL)"
           )

    create unique_index(:agent_inbox_events, [:agent_id, :idempotency_key],
             name: "agent_inbox_events_unique_idempotency_index",
             where: "(idempotency_key IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_inbox_events, [:agent_id, :idempotency_key],
                     name: "agent_inbox_events_unique_idempotency_index"
                   )

    drop_if_exists unique_index(:agent_inbox_events, [:agent_id, :content_hash],
                     name: "agent_inbox_events_unique_content_hash_index"
                   )

    drop constraint(:agent_inbox_events, "agent_inbox_events_agent_id_fkey")

    drop constraint(:agent_inbox_events, "agent_inbox_events_user_id_fkey")

    drop table(:agent_inbox_events)

    drop constraint(:agent_activity_logs, "agent_activity_logs_agent_id_fkey")

    drop constraint(:agent_activity_logs, "agent_activity_logs_user_id_fkey")

    drop table(:agent_activity_logs)
  end
end
