defmodule Magus.Repo.Migrations.RemoveAccessCountAndLastAccessedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memories) do
      remove :last_accessed_at
      remove :access_count
    end
  end

  def down do
    alter table(:memories) do
      add :access_count, :bigint, null: false, default: 0
      add :last_accessed_at, :utc_datetime_usec
    end
  end
end
