defmodule Magus.Repo.Migrations.AllowMultipleDraftsPerConversation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:drafts, [:conversation_id],
                     name: "drafts_unique_draft_per_conversation_index"
                   )
  end

  def down do
    create unique_index(:drafts, [:conversation_id],
             name: "drafts_unique_draft_per_conversation_index"
           )
  end
end
