defmodule Magus.Repo.Migrations.MemoryV2Simplification do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Old inactive (soft-deleted) memories predate is_active removal below.
    # The rebuilt unique indexes drop the is_active predicate and become
    # scope-only, so leftover inactive duplicates would violate them.
    execute("DELETE FROM memories WHERE is_active = false")

    drop table(:memory_associations)

    drop table(:memory_sources)

    drop table(:memory_versions)

    alter table(:memories) do
      remove :structured_data
      remove :confidence
      remove :last_accessed_at
      remove :is_active
    end

    drop_if_exists unique_index(:memories, [:custom_agent_id, :name],
                     name: "memories_unique_name_per_agent_index"
                   )

    drop_if_exists unique_index(:memories, [:conversation_id, :name],
                     name: "memories_unique_name_per_conversation_index"
                   )

    drop_if_exists unique_index(:memories, [:user_id, :workspace_id, :name],
                     name: "memories_unique_user_name_per_user_index"
                   )

    create unique_index(:memories, [:custom_agent_id, :name],
             name: "memories_unique_name_per_agent_index",
             where: "(scope = 'agent')"
           )

    create unique_index(:memories, [:conversation_id, :name],
             name: "memories_unique_name_per_conversation_index",
             where: "(scope = 'local')"
           )

    create unique_index(:memories, [:user_id, :workspace_id, :name],
             name: "memories_unique_user_name_per_user_index",
             nulls_distinct: false,
             where: "(scope = 'user')"
           )
  end

  def down do
    drop_if_exists unique_index(:memories, [:user_id, :workspace_id, :name],
                     name: "memories_unique_user_name_per_user_index"
                   )

    drop_if_exists unique_index(:memories, [:conversation_id, :name],
                     name: "memories_unique_name_per_conversation_index"
                   )

    drop_if_exists unique_index(:memories, [:custom_agent_id, :name],
                     name: "memories_unique_name_per_agent_index"
                   )

    create unique_index(:memories, [:user_id, :workspace_id, :name],
             name: "memories_unique_user_name_per_user_index",
             nulls_distinct: false,
             where: "(is_active = true AND scope = 'user')"
           )

    create unique_index(:memories, [:conversation_id, :name],
             name: "memories_unique_name_per_conversation_index",
             where: "(is_active = true AND scope = 'local')"
           )

    create unique_index(:memories, [:custom_agent_id, :name],
             name: "memories_unique_name_per_agent_index",
             where: "(is_active = true AND scope = 'agent')"
           )

    alter table(:memories) do
      add :is_active, :boolean, default: true
      add :last_accessed_at, :utc_datetime_usec
      add :confidence, :float, null: false, default: 1.0
      add :structured_data, :map
    end

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
