defmodule Magus.Repo.Migrations.CreateOrgTakeoverIntents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:org_takeover_intents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :account_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :stripe_subscription_id, :text, null: false
      add :refund_target, :text
      add :stripe_customer_id, :text
      add :refund_cents, :bigint
      add :refund_id, :text
      add :status, :text, null: false, default: "pending"
      add :attempts, :bigint, null: false, default: 0
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:org_takeover_intents, [:account_id, :organization_id],
             name: "org_takeover_intents_unique_account_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:org_takeover_intents, [:account_id, :organization_id],
                     name: "org_takeover_intents_unique_account_org_index"
                   )

    drop table(:org_takeover_intents)
  end
end
