defmodule Magus.Repo.Migrations.AddTestAccountFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :test_account, :boolean, null: false, default: false
      add :test_account_expires_at, :utc_datetime_usec
      add :test_account_password, :binary
    end
  end

  def down do
    alter table(:users) do
      remove :test_account_password
      remove :test_account_expires_at
      remove :test_account
    end
  end
end
