defmodule Magus.Repo.Migrations.AddModelProviders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:model_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :req_llm_id, :text, null: false
      add :base_url, :text
      add :api_key, :binary
      add :enabled?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:model_providers, [:slug], name: "model_providers_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:model_providers, [:slug],
                     name: "model_providers_unique_slug_index"
                   )

    drop table(:model_providers)
  end
end
