defmodule Magus.Repo.Migrations.AddExtractionIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:conversations, [:last_message_at],
             name: "conversations_needing_extraction_idx",
             where: "messages_since_extraction > 0"
           )
  end

  def down do
    drop_if_exists index(:conversations, [:last_message_at],
                     name: "conversations_needing_extraction_idx"
                   )
  end
end
