defmodule Magus.Repo.Migrations.MakeAnnouncementTitlesMultilang do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Convert existing string values to jsonb map format {"en": value}
    # and change column types in one go
    execute """
    ALTER TABLE announcements
      ALTER COLUMN title TYPE jsonb USING jsonb_build_object('en', title),
      ALTER COLUMN description TYPE jsonb USING jsonb_build_object('en', description)
    """
  end

  def down do
    execute """
    ALTER TABLE announcements
      ALTER COLUMN title TYPE text USING title->>'en',
      ALTER COLUMN description TYPE text USING description->>'en'
    """
  end
end
