defmodule Magus.Repo.Migrations.AddIntegrationConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:integration_conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :external_identifier, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_integration_id,
          references(:user_integrations,
            column: :id,
            name: "integration_conversations_user_integration_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "integration_conversations_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:integration_conversations, [:user_integration_id, :external_identifier],
             name: "integration_conversations_unique_integration_identifier_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :integration_conversations,
                     [:user_integration_id, :external_identifier],
                     name: "integration_conversations_unique_integration_identifier_index"
                   )

    drop constraint(
           :integration_conversations,
           "integration_conversations_user_integration_id_fkey"
         )

    drop constraint(:integration_conversations, "integration_conversations_conversation_id_fkey")

    drop table(:integration_conversations)
  end
end
