defmodule Magus.Repo.Migrations.DropMaxIterationsDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      modify :max_iterations, :bigint, default: nil
    end

    execute("UPDATE custom_agents SET max_iterations = NULL")
  end

  def down do
    alter table(:custom_agents) do
      modify :max_iterations, :bigint, default: 10
    end

    execute("UPDATE custom_agents SET max_iterations = 10 WHERE max_iterations IS NULL")
  end
end
