defmodule Magus.Repo.Migrations.CreateSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_usage_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :override_type, :text, null: false
      add :bonus_daily_premium_messages, :bigint, default: 0
      add :bonus_monthly_images, :bigint, default: 0
      add :bonus_monthly_videos, :bigint, default: 0
      add :bonus_storage_bytes, :bigint, default: 0
      add :exempt_from_limits, :boolean, null: false, default: false
      add :reason, :text
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_usage_overrides_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:user_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :stripe_customer_id, :text
      add :stripe_subscription_id, :text
      add :status, :text, null: false, default: "active"
      add :current_period_start, :utc_datetime_usec
      add :current_period_end, :utc_datetime_usec
      add :canceled_at, :utc_datetime_usec
      add :last_payment_status, :text
      add :storage_usage_bytes, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :usage_plan_id, :uuid, null: false
    end

    create table(:usage_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_subscriptions) do
      modify :usage_plan_id,
             references(:usage_plans,
               column: :id,
               name: "user_subscriptions_usage_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_subscriptions, [:user_id],
             name: "user_subscriptions_unique_user_index"
           )

    alter table(:usage_plans) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :price_monthly_cents, :bigint, null: false, default: 0
      add :stripe_price_id_monthly, :text
      add :stripe_price_id_yearly, :text
      add :daily_premium_messages, :bigint
      add :monthly_images, :bigint
      add :monthly_videos, :bigint
      add :storage_bytes, :bigint, null: false, default: 0
      add :max_upload_bytes, :bigint, null: false, default: 0
      add :is_active, :boolean, null: false, default: true
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:usage_plans, [:key], name: "usage_plans_unique_key_index")

    # Performance index for daily message counting queries
    # Query pattern: WHERE user_id = ? AND inserted_at >= ? AND inserted_at < ?
    create index(:message_usages, [:user_id, :inserted_at],
             name: "message_usages_user_id_inserted_at_index"
           )
  end

  def down do
    drop_if_exists index(:message_usages, [:user_id, :inserted_at],
                     name: "message_usages_user_id_inserted_at_index"
                   )

    drop_if_exists unique_index(:usage_plans, [:key], name: "usage_plans_unique_key_index")

    alter table(:usage_plans) do
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :is_active
      remove :max_upload_bytes
      remove :storage_bytes
      remove :monthly_videos
      remove :monthly_images
      remove :daily_premium_messages
      remove :stripe_price_id_yearly
      remove :stripe_price_id_monthly
      remove :price_monthly_cents
      remove :description
      remove :name
      remove :key
    end

    drop_if_exists unique_index(:user_subscriptions, [:user_id],
                     name: "user_subscriptions_unique_user_index"
                   )

    drop constraint(:user_subscriptions, "user_subscriptions_usage_plan_id_fkey")

    alter table(:user_subscriptions) do
      modify :usage_plan_id, :uuid
    end

    drop table(:usage_plans)

    drop constraint(:user_subscriptions, "user_subscriptions_user_id_fkey")

    drop table(:user_subscriptions)

    drop constraint(:user_usage_overrides, "user_usage_overrides_user_id_fkey")

    drop table(:user_usage_overrides)
  end
end
