defmodule Magus.Repo.Migrations.AddSkillBundleSha do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:skills) do
      add :bundle_sha, :text
    end

    # Backfill: existing content-addressed paths embed the sha in the basename
    # (bundle_path = "skills/<user_id>/<sha>.zip"). Parse it back out.
    execute("""
    UPDATE skills
    SET bundle_sha = split_part(split_part(bundle_path, '/', -1), '.', 1)
    WHERE bundle_path IS NOT NULL AND bundle_sha IS NULL
    """)
  end

  def down do
    alter table(:skills) do
      remove :bundle_sha
    end
  end
end
