defmodule Magus.Repo.Migrations.AddUsageMeterColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:platform_pricing) do
      add :stripe_usage_meter_id, :text
      add :stripe_usage_price_id, :text
    end
  end

  def down do
    alter table(:platform_pricing) do
      remove :stripe_usage_price_id
      remove :stripe_usage_meter_id
    end
  end
end
