defmodule Magus.Repo.Migrations.AddExtractionWatermark do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :last_extracted_message_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:conversations) do
      remove :last_extracted_message_at
    end
  end
end
