defmodule Magus.Repo.Migrations.CreateIntegrationsTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:integration_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :credential_type, :text, null: false
      add :encrypted_data, :binary, null: false
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_integration_id, :uuid, null: false
    end

    create table(:user_integrations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:integration_credentials) do
      modify :user_integration_id,
             references(:user_integrations,
               column: :id,
               name: "integration_credentials_user_integration_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:user_integrations) do
      add :status, :text, default: "pending"
      add :config, :map, default: %{}
      add :external_id, :text
      add :last_sync_at, :utc_datetime_usec
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_integrations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :provider_id, :uuid, null: false
    end

    create table(:integration_input_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider_key, :text, null: false
      add :external_id, :text
      add :message_type, :text, null: false
      add :payload, :map, null: false
      add :raw_payload, :map
      add :status, :text, default: "pending"
      add :processed_at, :utc_datetime_usec
      add :error_message, :text

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "integration_input_messages_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_integration_id,
          references(:user_integrations,
            column: :id,
            name: "integration_input_messages_user_integration_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :routed_to_conversation_id,
          references(:conversations,
            column: :id,
            name: "integration_input_messages_routed_to_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:integration_input_messages, [:provider_key, :external_id],
             name: "integration_input_messages_unique_external_index",
             where: "(external_id IS NOT NULL)"
           )

    create table(:integration_audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider_key, :text
      add :operation, :text, null: false
      add :status, :text, null: false
      add :ip_address, :text
      add :metadata, :map, default: %{}
      add :error_details, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "integration_audit_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:integration_output_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider_key, :text, null: false
      add :operation, :text, null: false
      add :payload, :map, null: false
      add :status, :text, default: "pending"
      add :external_id, :text
      add :sent_at, :utc_datetime_usec
      add :error_message, :text
      add :retry_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "integration_output_messages_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_integration_id,
          references(:user_integrations,
            column: :id,
            name: "integration_output_messages_user_integration_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :triggered_by_input_id,
          references(:integration_input_messages,
            column: :id,
            name: "integration_output_messages_triggered_by_input_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:integration_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_integrations) do
      modify :provider_id,
             references(:integration_providers,
               column: :id,
               name: "user_integrations_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_integrations, [:user_id, :provider_id],
             name: "user_integrations_unique_user_provider_index"
           )

    alter table(:integration_providers) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :auth_type, :text, null: false
      add :supports_input?, :boolean, default: false
      add :supports_output?, :boolean, default: false
      add :operations, {:array, :text}, default: []
      add :config_schema, :map, default: %{}
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:integration_providers, [:key],
             name: "integration_providers_unique_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:integration_providers, [:key],
                     name: "integration_providers_unique_key_index"
                   )

    alter table(:integration_providers) do
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :config_schema
      remove :operations
      remove :supports_output?
      remove :supports_input?
      remove :auth_type
      remove :description
      remove :name
      remove :key
    end

    drop_if_exists unique_index(:user_integrations, [:user_id, :provider_id],
                     name: "user_integrations_unique_user_provider_index"
                   )

    drop constraint(:user_integrations, "user_integrations_provider_id_fkey")

    alter table(:user_integrations) do
      modify :provider_id, :uuid
    end

    drop table(:integration_providers)

    drop constraint(:integration_output_messages, "integration_output_messages_user_id_fkey")

    drop constraint(
           :integration_output_messages,
           "integration_output_messages_user_integration_id_fkey"
         )

    drop constraint(
           :integration_output_messages,
           "integration_output_messages_triggered_by_input_id_fkey"
         )

    drop table(:integration_output_messages)

    drop constraint(:integration_audit_logs, "integration_audit_logs_user_id_fkey")

    drop table(:integration_audit_logs)

    drop_if_exists unique_index(:integration_input_messages, [:provider_key, :external_id],
                     name: "integration_input_messages_unique_external_index"
                   )

    drop constraint(:integration_input_messages, "integration_input_messages_user_id_fkey")

    drop constraint(
           :integration_input_messages,
           "integration_input_messages_user_integration_id_fkey"
         )

    drop constraint(
           :integration_input_messages,
           "integration_input_messages_routed_to_conversation_id_fkey"
         )

    drop table(:integration_input_messages)

    drop constraint(:user_integrations, "user_integrations_user_id_fkey")

    alter table(:user_integrations) do
      remove :provider_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :error_message
      remove :last_sync_at
      remove :external_id
      remove :config
      remove :status
    end

    drop constraint(:integration_credentials, "integration_credentials_user_integration_id_fkey")

    alter table(:integration_credentials) do
      modify :user_integration_id, :uuid
    end

    drop table(:user_integrations)

    drop table(:integration_credentials)
  end
end
