defmodule Magus.Repo.Migrations.AddCurrentWorkspaceIdToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :current_workspace_id, :uuid
    end
  end

  def down do
    alter table(:users) do
      remove :current_workspace_id
    end
  end
end
