defmodule Magus.Repo.Migrations.AddParentPageToBrainPages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brain_pages) do
      add :depth, :bigint, null: false, default: 0

      add :parent_page_id,
          references(:brain_pages,
            column: :id,
            name: "brain_pages_parent_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:brain_pages, [:parent_page_id])
  end

  def down do
    drop constraint(:brain_pages, "brain_pages_parent_page_id_fkey")

    alter table(:brain_pages) do
      remove :parent_page_id
      remove :depth
    end
  end
end
