defmodule Magus.Repo.Migrations.AddWalletAndPricingTiers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_subscriptions) do
      add :billing_interval, :text, null: false, default: "monthly"
      add :wallet_balance_cents, :bigint, null: false, default: 0
      add :period_usage_cents, :bigint, null: false, default: 0
      add :monthly_spend_cap_cents, :bigint
      add :auto_recharge_enabled, :boolean, null: false, default: false
      add :auto_recharge_amount_cents, :bigint
      add :auto_recharge_threshold_cents, :bigint
    end

    create table(:platform_pricing, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :is_singleton, :boolean, null: false, default: true
      add :paying_user_high_water_mark, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :current_tier_id, :uuid
    end

    create table(:pricing_tiers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:platform_pricing) do
      modify :current_tier_id,
             references(:pricing_tiers,
               column: :id,
               name: "platform_pricing_current_tier_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:platform_pricing, [:is_singleton],
             name: "platform_pricing_singleton_index"
           )

    alter table(:pricing_tiers) do
      add :min_users, :bigint, null: false
      add :monthly_price_cents, :bigint, null: false
      add :annual_price_cents, :bigint, null: false
      add :stripe_price_id_monthly, :text
      add :stripe_price_id_annual, :text
      add :is_active, :boolean, null: false, default: true
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:pricing_tiers, [:min_users],
             name: "pricing_tiers_unique_min_users_index"
           )
  end

  def down do
    drop_if_exists unique_index(:pricing_tiers, [:min_users],
                     name: "pricing_tiers_unique_min_users_index"
                   )

    alter table(:pricing_tiers) do
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :is_active
      remove :stripe_price_id_annual
      remove :stripe_price_id_monthly
      remove :annual_price_cents
      remove :monthly_price_cents
      remove :min_users
    end

    drop_if_exists unique_index(:platform_pricing, [:is_singleton],
                     name: "platform_pricing_singleton_index"
                   )

    drop constraint(:platform_pricing, "platform_pricing_current_tier_id_fkey")

    alter table(:platform_pricing) do
      modify :current_tier_id, :uuid
    end

    drop table(:pricing_tiers)

    drop table(:platform_pricing)

    alter table(:user_subscriptions) do
      remove :auto_recharge_threshold_cents
      remove :auto_recharge_amount_cents
      remove :auto_recharge_enabled
      remove :monthly_spend_cap_cents
      remove :period_usage_cents
      remove :wallet_balance_cents
      remove :billing_interval
    end
  end
end
