defmodule Magus.Repo.Migrations.AddModelOptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :options, :map
    end
  end

  def down do
    alter table(:models) do
      remove :options
    end
  end
end
