defmodule Magus.Repo.Migrations.AddDataRegionFieldsToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :data_region_preference, {:array, :text},
        null: false,
        default: fragment("ARRAY['US','EU','CH']::text[]")

      add :data_region_consents, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:users) do
      remove :data_region_consents
      remove :data_region_preference
    end
  end
end
