defmodule Magus.Repo.Migrations.AddMemoryScopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memories) do
      add :scope, :text, null: false, default: "local"
    end

    drop_if_exists unique_index(:memories, [:conversation_id, :name],
                     name: "memories_unique_name_per_conversation_index"
                   )

    alter table(:memories) do
      modify :conversation_id, :uuid, null: true
    end

    create unique_index(:memories, [:conversation_id, :name],
             name: "memories_unique_name_per_conversation_index",
             where: "(is_active = true AND scope = 'local')"
           )

    create unique_index(:memories, [:user_id, :name],
             name: "memories_unique_global_name_per_user_index",
             where: "(is_active = true AND scope = 'global')"
           )

    # Index for fetching global memories by user sorted by last access
    create index(:memories, [:user_id, :scope, :last_accessed_at],
             name: "memories_global_by_user_index",
             where: "scope = 'global'"
           )

    execute("""
    ALTER TABLE memories ADD CONSTRAINT memories_local_requires_conversation CHECK (scope = 'global' OR conversation_id IS NOT NULL)
    """)
  end

  def down do
    execute("""
    ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_local_requires_conversation
    """)

    drop_if_exists index(:memories, [:user_id, :scope, :last_accessed_at],
                     name: "memories_global_by_user_index"
                   )

    drop_if_exists unique_index(:memories, [:user_id, :name],
                     name: "memories_unique_global_name_per_user_index"
                   )

    drop_if_exists unique_index(:memories, [:conversation_id, :name],
                     name: "memories_unique_name_per_conversation_index"
                   )

    alter table(:memories) do
      modify :conversation_id, :uuid, null: false
    end

    create unique_index(:memories, [:conversation_id, :name],
             name: "memories_unique_name_per_conversation_index",
             where: "(is_active = true)"
           )

    alter table(:memories) do
      remove :scope
    end
  end
end
