defmodule Magus.Repo.Migrations.AddExtraSeatsToUserSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_subscriptions) do
      add :extra_seats, :bigint, null: false, default: 0
      add :stripe_subscription_item_id, :text
    end
  end

  def down do
    alter table(:user_subscriptions) do
      remove :stripe_subscription_item_id
      remove :extra_seats
    end
  end
end
