defmodule Magus.Repo.Migrations.CreateKnowledgeAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_access, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :grantee_type, :text, null: false
      add :grantee_id, :uuid, null: false
      add :can_write, :boolean, null: false, default: false
      add :granted_by_id, :uuid
      add :granted_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_collection_id,
          references(:knowledge_collections,
            column: :id,
            name: "knowledge_access_knowledge_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :file_id,
          references(:files,
            column: :id,
            name: "knowledge_access_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:knowledge_access, [:knowledge_collection_id, :grantee_type, :grantee_id],
             name: "knowledge_access_unique_collection_grant_index",
             where: "(knowledge_collection_id IS NOT NULL)"
           )

    create unique_index(:knowledge_access, [:file_id, :grantee_type, :grantee_id],
             name: "knowledge_access_unique_file_grant_index",
             where: "(file_id IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_access, [:file_id, :grantee_type, :grantee_id],
                     name: "knowledge_access_unique_file_grant_index"
                   )

    drop_if_exists unique_index(
                     :knowledge_access,
                     [:knowledge_collection_id, :grantee_type, :grantee_id],
                     name: "knowledge_access_unique_collection_grant_index"
                   )

    drop constraint(:knowledge_access, "knowledge_access_knowledge_collection_id_fkey")

    drop constraint(:knowledge_access, "knowledge_access_file_id_fkey")

    drop table(:knowledge_access)
  end
end
