defmodule Magus.Repo.Migrations.AddSuperBrainEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:super_brain_episodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :graph_name, :text, null: false
      add :raw_text, :text, null: false
      add :content_fingerprint, :binary, null: false
      add :source_weight, :float, null: false, default: 1.0
      add :extractor_version, :text
      add :status, :text, null: false, default: "pending"
      add :attempt_count, :bigint, null: false, default: 0
      add :last_error, :text
      add :extraction_model, :text
      add :extracted_at, :utc_datetime_usec

      add :source_user_id,
          references(:users,
            column: :id,
            name: "super_brain_episodes_source_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:super_brain_episodes, [:resource_type, :resource_id],
             name: "super_brain_episodes_unique_resource_index"
           )
  end

  def down do
    drop_if_exists unique_index(:super_brain_episodes, [:resource_type, :resource_id],
                     name: "super_brain_episodes_unique_resource_index"
                   )

    drop constraint(:super_brain_episodes, "super_brain_episodes_source_user_id_fkey")

    drop table(:super_brain_episodes)
  end
end
