defmodule Magus.Repo.Migrations.AddSoftDeleteToConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :deleted_at, :utc_datetime_usec
    end

    create index(:conversations, [:deleted_at], where: "deleted_at IS NOT NULL")
  end

  def down do
    drop_if_exists index(:conversations, [:deleted_at])

    alter table(:conversations) do
      remove :deleted_at
    end
  end
end
