defmodule Magus.Repo.Migrations.AddFileProcessingRetryState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :processing_attempts, :bigint, null: false, default: 0
      add :transient_error, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:files) do
      remove :transient_error
      remove :processing_attempts
    end
  end
end
