defmodule Magus.Repo.Migrations.RebuildMemoryUserIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:memories, [:user_id, :name],
                     name: "memories_unique_user_name_per_user_index"
                   )

    create unique_index(:memories, [:user_id, :workspace_id, :name],
             name: "memories_unique_user_name_per_user_index",
             nulls_distinct: false,
             where: "(is_active = true AND scope = 'user')"
           )
  end

  def down do
    drop_if_exists unique_index(:memories, [:user_id, :workspace_id, :name],
                     name: "memories_unique_user_name_per_user_index"
                   )

    create unique_index(:memories, [:user_id, :name],
             name: "memories_unique_user_name_per_user_index",
             where: "(is_active = true AND scope = 'user')"
           )
  end
end
