defmodule Magus.Repo.Migrations.AddMessageUsageCostFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message_usages) do
      add :total_cost, :decimal, default: "0"
      add :provider_cost, :decimal
      add :finish_reason, :text
    end
  end

  def down do
    alter table(:message_usages) do
      remove :finish_reason
      remove :provider_cost
      remove :total_cost
    end
  end
end
