defmodule Magus.Repo.Migrations.AddImagePathToCustomAgents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      add :image_path, :text
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :image_path
    end
  end
end
