defmodule Magus.Repo.Migrations.AddServicePort do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sandboxes) do
      add :service_port, :bigint
    end
  end

  def down do
    alter table(:sandboxes) do
      remove :service_port
    end
  end
end
