defmodule Magus.Repo.Migrations.AddAllowedProvidersToModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :allowed_providers, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:models) do
      remove :allowed_providers
    end
  end
end
