defmodule Magus.Repo.Migrations.AddConversationRelationshipToActivityLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_activity_logs) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "agent_activity_logs_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:agent_activity_logs, [:conversation_id])
  end

  def down do
    drop_if_exists index(:agent_activity_logs, [:conversation_id])

    drop constraint(:agent_activity_logs, "agent_activity_logs_conversation_id_fkey")

    alter table(:agent_activity_logs) do
      modify :conversation_id, :uuid
    end
  end
end
