defmodule Magus.Repo.Migrations.CreateApiTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :key_hash, :text, null: false
      add :key_prefix, :text, null: false
      add :scope, :text, null: false, default: "read"
      add :last_used_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec
      add :created_via, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "api_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "api_tokens_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:api_tokens, [:user_id])

    create index(:api_tokens, [:key_hash], unique: true)
  end

  def down do
    drop constraint(:api_tokens, "api_tokens_user_id_fkey")

    drop constraint(:api_tokens, "api_tokens_workspace_id_fkey")

    drop_if_exists index(:api_tokens, [:key_hash])

    drop_if_exists index(:api_tokens, [:user_id])

    drop table(:api_tokens)
  end
end
