defmodule Magus.Repo.Migrations.AddSkillToolsToConversation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :skill_tools, {:array, :text}
    end
  end

  def down do
    alter table(:conversations) do
      remove :skill_tools
    end
  end
end
