defmodule Magus.Repo.Migrations.AddModelCostStructuredFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :input_cost_value, :decimal
      add :output_cost_value, :decimal
      add :input_cost_unit, :text, null: false, default: "per_million_tokens"
      add :output_cost_unit, :text, null: false, default: "per_million_tokens"
    end
  end

  def down do
    alter table(:models) do
      remove :output_cost_unit
      remove :input_cost_unit
      remove :output_cost_value
      remove :input_cost_value
    end
  end
end
