defmodule Magus.Repo.Migrations.AddDefaultAssignee do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_tasks) do
      modify :assigned_to_agent, :text, default: "assistant"
    end
  end

  def down do
    alter table(:plan_tasks) do
      modify :assigned_to_agent, :text, default: nil
    end
  end
end
