defmodule Magus.Repo.Migrations.AddWorkspaceToConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :workspace_visibility, :text, default: "private"

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "conversations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_workspace_id_fkey")

    alter table(:conversations) do
      remove :workspace_id
      remove :workspace_visibility
    end
  end
end
