defmodule Magus.Repo.Migrations.AddSelectedPlanKeyToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :selected_plan_key, :text
    end
  end

  def down do
    alter table(:users) do
      remove :selected_plan_key
    end
  end
end
