defmodule Magus.Repo.Migrations.AddFeatureUsageEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:feature_usage_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :feature, :text, null: false
      add :action, :text, null: false
      add :metadata, :map, default: %{}

      add :user_id,
          references(:users,
            column: :id,
            name: "feature_usage_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:feature_usage_events, "feature_usage_events_user_id_fkey")

    drop table(:feature_usage_events)
  end
end
