defmodule Magus.Repo.Migrations.AddModelSubscriptionFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :is_free, :boolean, null: false, default: false
      add :cost_multiplier, :decimal, null: false, default: "1.0"
    end
  end

  def down do
    alter table(:models) do
      remove :cost_multiplier
      remove :is_free
    end
  end
end
