defmodule Magus.Repo.Migrations.AddProviderToMessageUsages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message_usages) do
      add :provider, :text
    end
  end

  def down do
    alter table(:message_usages) do
      remove :provider
    end
  end
end
