defmodule Magus.Repo.Migrations.RemoveIsFreeFromModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      remove :is_free
    end
  end

  def down do
    alter table(:models) do
      add :is_free, :boolean, null: false, default: false
    end
  end
end
