defmodule Magus.Repo.Migrations.RenameConversationStartersToSlashCommands do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:custom_agents) do
      remove :conversation_starters
      add :slash_commands, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:custom_agents) do
      remove :slash_commands
      add :conversation_starters, {:array, :text}, default: []
    end
  end
end
