defmodule Magus.Repo.Migrations.AddConversationSkillApprovals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversation_skill_approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :bundle_sha, :text
      add :source, :text, null: false, default: "approval_card"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_skill_approvals_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :skill_id,
          references(:skills,
            column: :id,
            name: "conversation_skill_approvals_skill_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :approved_by_id,
          references(:users,
            column: :id,
            name: "conversation_skill_approvals_approved_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:conversation_skill_approvals, [:conversation_id, :skill_id],
             name: "conversation_skill_approvals_unique_conversation_skill_index"
           )
  end

  def down do
    drop constraint(
           :conversation_skill_approvals,
           "conversation_skill_approvals_conversation_id_fkey"
         )

    drop constraint(:conversation_skill_approvals, "conversation_skill_approvals_skill_id_fkey")

    drop constraint(
           :conversation_skill_approvals,
           "conversation_skill_approvals_approved_by_id_fkey"
         )

    drop_if_exists unique_index(:conversation_skill_approvals, [:conversation_id, :skill_id],
                     name: "conversation_skill_approvals_unique_conversation_skill_index"
                   )

    drop table(:conversation_skill_approvals)
  end
end
