defmodule Magus.Repo.Migrations.AddDispatchedToInputMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:integration_input_messages) do
      add :dispatched, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:integration_input_messages) do
      remove :dispatched
    end
  end
end
