defmodule Magus.Repo.Migrations.AddConversationSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :system_prompt, :text
      add :sampling_settings, :map
    end
  end

  def down do
    alter table(:conversations) do
      remove :sampling_settings
      remove :system_prompt
    end
  end
end
