defmodule Magus.Repo.Migrations.ApplyMemoryWorkspaceReviewFixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Index already created by prior migration
    # 20260425094756_add_workspace_id_to_memories.exs (the auto-generated default
    # name matches the explicit name we now declare via custom_indexes). This
    # migration only updates the resource snapshot to record the index there;
    # use if_not_exists so the create is a no-op against existing databases.
    create_if_not_exists index(:memories, [:workspace_id, :user_id],
                           name: "memories_workspace_id_user_id_index"
                         )
  end

  def down do
    drop_if_exists index(:memories, [:workspace_id, :user_id],
                     name: "memories_workspace_id_user_id_index"
                   )
  end
end
