defmodule Magus.Repo.Migrations.CreateKnowledgeSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :provider, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :auth_config, :binary, null: false
      add :settings, :map, default: %{}
      add :last_error, :text
      add :connected_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "knowledge_sources_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "knowledge_sources_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:knowledge_sources, "knowledge_sources_user_id_fkey")

    drop constraint(:knowledge_sources, "knowledge_sources_workspace_id_fkey")

    drop table(:knowledge_sources)
  end
end
