defmodule Magus.Repo.Migrations.AddMentionsSupport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Step 1: Add handle column as nullable first
    alter table(:custom_agents) do
      add :handle, :text
    end

    flush()

    # Step 2: Backfill handles from names for existing agents.
    # Generates lowercase slugs; appends suffix for per-user uniqueness.
    execute """
    WITH slugged AS (
      SELECT
        id,
        user_id,
        COALESCE(
          NULLIF(
            regexp_replace(
              regexp_replace(lower(name), '[^\\w]+', '-', 'g'),
              '^-|-$', '', 'g'
            ),
            ''
          ),
          'agent'
        ) AS base_handle
      FROM custom_agents
    ),
    ranked AS (
      SELECT
        id,
        base_handle,
        ROW_NUMBER() OVER (PARTITION BY user_id, base_handle ORDER BY id) AS rn
      FROM slugged
    )
    UPDATE custom_agents
    SET handle = CASE
      WHEN ranked.rn = 1 THEN ranked.base_handle
      ELSE ranked.base_handle || '-' || ranked.rn
    END
    FROM ranked
    WHERE custom_agents.id = ranked.id
    """

    flush()

    # Step 3: Now make it NOT NULL
    alter table(:custom_agents) do
      modify :handle, :text, null: false
    end

    # Step 4: Add unique index
    create unique_index(:custom_agents, [:handle, :user_id],
             name: "custom_agents_unique_handle_per_user_index"
           )

    # Step 5: Add responding_agent_id to messages
    alter table(:messages) do
      add :responding_agent_id,
          references(:custom_agents,
            column: :id,
            name: "messages_responding_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:messages, "messages_responding_agent_id_fkey")

    alter table(:messages) do
      remove :responding_agent_id
    end

    drop_if_exists unique_index(:custom_agents, [:handle, :user_id],
                     name: "custom_agents_unique_handle_per_user_index"
                   )

    alter table(:custom_agents) do
      remove :handle
    end
  end
end
