defmodule Magus.Repo.Migrations.AddAgentAssignmentToPlanTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_tasks) do
      add :assigned_to_custom_agent_id, :uuid
      add :blocked_reason, :text
      add :waiting_on_user, :boolean, default: false
    end
  end

  def down do
    alter table(:plan_tasks) do
      remove :waiting_on_user
      remove :blocked_reason
      remove :assigned_to_custom_agent_id
    end
  end
end
