defmodule Magus.Repo.Migrations.AddCascadeDeleteToShareLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:conversation_share_links, "conversation_share_links_conversation_id_fkey")

    alter table(:conversation_share_links) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_share_links_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:conversation_share_links, "conversation_share_links_conversation_id_fkey")

    alter table(:conversation_share_links) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_share_links_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
