defmodule Magus.Repo.Migrations.AddBrainInstructions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brains) do
      add :instructions, :text
    end
  end

  def down do
    alter table(:brains) do
      remove :instructions
    end
  end
end
