defmodule Magus.Repo.Migrations.UpdateCustomAgentsIndexesForSoftDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:custom_agents, [:user_id],
                     name: "custom_agents_unique_default_index"
                   )

    drop_if_exists unique_index(:custom_agents, [:handle, :user_id],
                     name: "custom_agents_unique_handle_per_user_index"
                   )

    create unique_index(:custom_agents, [:user_id],
             name: "custom_agents_unique_default_index",
             where: "(is_default = true) AND (deleted_at IS NULL)"
           )

    create unique_index(:custom_agents, [:handle, :user_id],
             where: "(deleted_at IS NULL)",
             name: "custom_agents_unique_handle_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:custom_agents, [:handle, :user_id],
                     name: "custom_agents_unique_handle_per_user_index"
                   )

    drop_if_exists unique_index(:custom_agents, [:user_id],
                     name: "custom_agents_unique_default_index"
                   )

    create unique_index(:custom_agents, [:handle, :user_id],
             name: "custom_agents_unique_handle_per_user_index"
           )

    create unique_index(:custom_agents, [:user_id],
             name: "custom_agents_unique_default_index",
             where: "(is_default = true)"
           )
  end
end
