defmodule Magus.Repo.Migrations.ReplacePinningWithAccessCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memories) do
      remove :is_pinned
      add :access_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:memories) do
      remove :access_count
      add :is_pinned, :boolean, default: false
    end
  end
end
