defmodule Magus.Repo.Migrations.DropDefaultModelFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      remove :default_video?
      remove :default_image?
      remove :default?
    end
  end

  def down do
    alter table(:models) do
      add :default?, :boolean, null: false, default: false
      add :default_image?, :boolean, null: false, default: false
      add :default_video?, :boolean, null: false, default: false
    end
  end
end
