defmodule Magus.Repo.Migrations.AddModelOwnership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :owner_user_id, :uuid
    end
  end

  def down do
    alter table(:models) do
      remove :owner_user_id
    end
  end
end
