defmodule Magus.Repo.Migrations.UpdateBrainsForBrainDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:brains) do
      remove :custom_agent_id
      remove :is_active
      remove :settings
      remove :helix_brain_id
      remove :name
    end

    drop constraint(:brains, "brains_user_id_fkey")

    alter table(:brains) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :title, :text, null: false
      add :slug, :text, null: false
      add :icon, :text
      add :color, :text
      add :is_archived, :boolean, default: false

      modify :user_id,
             references(:users,
               column: :id,
               name: "brains_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             ),
             null: false
    end

    create unique_index(:brains, [:user_id, :slug], name: "brains_unique_slug_per_user_index")
  end

  def down do
    drop_if_exists unique_index(:brains, [:user_id, :slug],
                     name: "brains_unique_slug_per_user_index"
                   )

    drop constraint(:brains, "brains_user_id_fkey")

    alter table(:brains) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "brains_user_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true

      remove :is_archived
      remove :color
      remove :icon
      remove :slug
      remove :title
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:brains) do
      add :name, :text, null: false
      add :helix_brain_id, :text
      add :settings, :map, default: %{}
      add :is_active, :boolean, default: true

      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "brains_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
