defmodule Magus.Repo.Migrations.AddPersonasFeature do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:personas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :system_prompt, :text, null: false
      add :chat_mode, :text
      add :is_public, :boolean, default: false
      add :published_at, :utc_datetime_usec
      add :is_highlighted, :boolean, default: false
      add :copy_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "personas_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :model_id,
          references(:models,
            column: :id,
            name: "personas_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :copied_from_id,
          references(:personas,
            column: :id,
            name: "personas_copied_from_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:persona_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :persona_id,
          references(:personas,
            column: :id,
            name: "persona_tags_persona_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "persona_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:persona_tags, [:persona_id, :tag_id],
             name: "persona_tags_unique_persona_tag_index"
           )

    create table(:persona_prompts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :persona_id,
          references(:personas,
            column: :id,
            name: "persona_prompts_persona_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :prompt_id,
          references(:prompts,
            column: :id,
            name: "persona_prompts_prompt_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:persona_prompts, [:persona_id, :prompt_id],
             name: "persona_prompts_unique_prompt_in_persona_index"
           )

    create table(:persona_favorites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "persona_favorites_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :persona_id,
          references(:personas,
            column: :id,
            name: "persona_favorites_persona_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:persona_favorites, [:user_id, :persona_id],
             name: "persona_favorites_unique_user_persona_favorite_index"
           )

    alter table(:conversations) do
      add :active_persona_id,
          references(:personas,
            column: :id,
            name: "conversations_active_persona_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:conversations, "conversations_active_persona_id_fkey")

    alter table(:conversations) do
      remove :active_persona_id
    end

    drop_if_exists unique_index(:persona_favorites, [:user_id, :persona_id],
                     name: "persona_favorites_unique_user_persona_favorite_index"
                   )

    drop constraint(:persona_favorites, "persona_favorites_user_id_fkey")

    drop constraint(:persona_favorites, "persona_favorites_persona_id_fkey")

    drop table(:persona_favorites)

    drop_if_exists unique_index(:persona_prompts, [:persona_id, :prompt_id],
                     name: "persona_prompts_unique_prompt_in_persona_index"
                   )

    drop constraint(:persona_prompts, "persona_prompts_persona_id_fkey")

    drop constraint(:persona_prompts, "persona_prompts_prompt_id_fkey")

    drop table(:persona_prompts)

    drop_if_exists unique_index(:persona_tags, [:persona_id, :tag_id],
                     name: "persona_tags_unique_persona_tag_index"
                   )

    drop constraint(:persona_tags, "persona_tags_persona_id_fkey")

    drop constraint(:persona_tags, "persona_tags_tag_id_fkey")

    drop table(:persona_tags)

    drop constraint(:personas, "personas_user_id_fkey")

    drop constraint(:personas, "personas_model_id_fkey")

    drop constraint(:personas, "personas_copied_from_id_fkey")

    drop table(:personas)
  end
end
