defmodule Magus.Repo.Migrations.AddSubAgentRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sub_agent_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :parent_conversation_id,
          references(:conversations,
            column: :id,
            name: "sub_agent_runs_parent_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :child_conversation_id,
          references(:conversations,
            column: :id,
            name: "sub_agent_runs_child_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "sub_agent_runs_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :model_key, :text, null: false
      add :objective, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :result_text, :text
      add :error_message, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :last_heartbeat_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:sub_agent_runs, "sub_agent_runs_parent_conversation_id_fkey")

    drop constraint(:sub_agent_runs, "sub_agent_runs_child_conversation_id_fkey")

    drop constraint(:sub_agent_runs, "sub_agent_runs_custom_agent_id_fkey")

    drop table(:sub_agent_runs)
  end
end
