defmodule Magus.Repo.Migrations.AddKeyHashToCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:integration_credentials) do
      add :key_hash, :text
    end

    create unique_index(:integration_credentials, [:key_hash],
             name: "integration_credentials_key_hash_index",
             where: "(key_hash IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:integration_credentials, [:key_hash],
                     name: "integration_credentials_key_hash_index"
                   )

    alter table(:integration_credentials) do
      remove :key_hash
    end
  end
end
