defmodule Magus.Repo.Migrations.CreateSuperBrainSuperGraphs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:super_brain_super_graphs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :accessor_type, :text, null: false
      add :user_id, :uuid, null: false
      add :workspace_id, :uuid
      add :graph_name, :text, null: false
      add :last_built_at, :utc_datetime_usec
      add :last_build_status, :text, null: false, default: "pending"
      add :last_build_duration_ms, :bigint
      add :last_error, :text
      add :read_set_snapshot, {:array, :map}, default: []
      add :canonical_entity_count, :bigint, null: false, default: 0
      add :canonical_edge_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:super_brain_super_graphs, [:accessor_type, :user_id, :workspace_id],
             name: "super_brain_super_graphs_unique_accessor_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(
                     :super_brain_super_graphs,
                     [:accessor_type, :user_id, :workspace_id],
                     name: "super_brain_super_graphs_unique_accessor_index"
                   )

    drop table(:super_brain_super_graphs)
  end
end
