defmodule Magus.Repo.Migrations.AddInviteExpiresAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspace_members) do
      add :invite_expires_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:workspace_members) do
      remove :invite_expires_at
    end
  end
end
