defmodule Magus.Repo.Migrations.DropWalletBalanceCents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_subscriptions) do
      remove :wallet_balance_cents
    end
  end

  def down do
    alter table(:user_subscriptions) do
      add :wallet_balance_cents, :bigint, null: false, default: 0
    end
  end
end
