defmodule Magus.Repo.Migrations.AddIntegrationHealthFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_integrations) do
      add :consecutive_failures, :bigint, null: false, default: 0
      add :last_error, :text
      add :last_success_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:user_integrations) do
      remove :last_success_at
      remove :last_error
      remove :consecutive_failures
    end
  end
end
