defmodule Magus.Repo.Migrations.DropViewCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:prompts) do
      remove :view_count
    end
  end

  def down do
    alter table(:prompts) do
      add :view_count, :bigint, default: 0
    end
  end
end
