defmodule Magus.Repo.Migrations.AddExtractionTrackingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :last_extraction_at, :utc_datetime_usec
      add :messages_since_extraction, :bigint, null: false, default: 0
      add :last_message_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:conversations) do
      remove :last_message_at
      remove :messages_since_extraction
      remove :last_extraction_at
    end
  end
end
