defmodule Magus.Repo.Migrations.AddDraftPaneStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:draft_pane_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :pane_open, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :draft_id,
          references(:drafts,
            column: :id,
            name: "draft_pane_states_draft_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "draft_pane_states_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:draft_pane_states, [:draft_id, :user_id],
             name: "draft_pane_states_unique_draft_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:draft_pane_states, [:draft_id, :user_id],
                     name: "draft_pane_states_unique_draft_user_index"
                   )

    drop constraint(:draft_pane_states, "draft_pane_states_draft_id_fkey")

    drop constraint(:draft_pane_states, "draft_pane_states_user_id_fkey")

    drop table(:draft_pane_states)
  end
end
