defmodule Magus.Repo.Migrations.AddWorkspaceIdToKnowledgeCollections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_collections) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "knowledge_collections_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    execute """
    UPDATE knowledge_collections kc
    SET workspace_id = ks.workspace_id
    FROM knowledge_sources ks
    WHERE kc.knowledge_source_id = ks.id AND ks.workspace_id IS NOT NULL
    """
  end

  def down do
    drop constraint(:knowledge_collections, "knowledge_collections_workspace_id_fkey")

    alter table(:knowledge_collections) do
      remove :workspace_id
    end
  end
end
