defmodule Magus.Repo.Migrations.AddCustomAgentToUserIntegrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Existing integrations are user-scoped (no agent binding).
    # Phase 2b requires agent-scoped integrations — clean slate.
    execute("TRUNCATE user_integrations CASCADE")

    alter table(:user_integrations) do
      add :custom_agent_id,
          references(:custom_agents,
            column: :id,
            name: "user_integrations_custom_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:user_integrations, [:user_id, :provider_id],
                     name: "user_integrations_unique_user_provider_index"
                   )

    create unique_index(:user_integrations, [:custom_agent_id, :provider_id],
             name: "user_integrations_unique_agent_provider_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_integrations, [:custom_agent_id, :provider_id],
                     name: "user_integrations_unique_agent_provider_index"
                   )

    create unique_index(:user_integrations, [:user_id, :provider_id],
             name: "user_integrations_unique_user_provider_index"
           )

    drop constraint(:user_integrations, "user_integrations_custom_agent_id_fkey")

    alter table(:user_integrations) do
      remove :custom_agent_id
    end
  end
end
