defmodule Magus.Repo.Migrations.AddAnnouncements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:announcements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false
      add :title, :text, null: false
      add :description, :text, null: false
      add :icon, :text, default: ""
      add :action_type, :text, null: false
      add :action_payload, :text, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:announcements, [:key], name: "announcements_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:announcements, [:key], name: "announcements_unique_key_index")

    drop table(:announcements)
  end
end
