defmodule Magus.Repo.Migrations.AddIndexesAndTimestampsToWorkflows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:job_runs, [:response_message_id])

    create index(:job_runs, [:trigger_message_id])

    alter table(:job_notification_preferences) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:job_notification_preferences) do
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists index(:job_runs, [:trigger_message_id])

    drop_if_exists index(:job_runs, [:response_message_id])
  end
end
