defmodule Magus.Repo.Migrations.AddWorkspaceIdToMemories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memories) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "memories_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:memories, [:workspace_id, :user_id])
  end

  def down do
    drop index(:memories, [:workspace_id, :user_id])
    drop constraint(:memories, "memories_workspace_id_fkey")

    alter table(:memories) do
      remove :workspace_id
    end
  end
end
