defmodule Magus.Repo.Migrations.AddUserIdToInputMessageUniqueIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:integration_input_messages, [:provider_key, :external_id],
                     name: "integration_input_messages_unique_external_index"
                   )

    create unique_index(:integration_input_messages, [:user_id, :provider_key, :external_id],
             name: "integration_input_messages_unique_external_index",
             where: "(external_id IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :integration_input_messages,
                     [:user_id, :provider_key, :external_id],
                     name: "integration_input_messages_unique_external_index"
                   )

    create unique_index(:integration_input_messages, [:provider_key, :external_id],
             name: "integration_input_messages_unique_external_index",
             where: "(external_id IS NOT NULL)"
           )
  end
end
