defmodule Magus.Repo.Migrations.AddProviderOwnership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:model_providers) do
      add :owner_user_id, :uuid
      add :validation_status, :text, null: false, default: "pending"
      add :last_validated_at, :utc_datetime
    end
  end

  def down do
    alter table(:model_providers) do
      remove :last_validated_at
      remove :validation_status
      remove :owner_user_id
    end
  end
end
