defmodule Magus.Repo.Migrations.AddSmartInboxEnhancements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:curation_inbox_items) do
      add :relevance_score, :bigint
      add :is_bookmarked, :boolean, null: false, default: false
      add :bookmarked_at, :utc_datetime_usec
      add :dismissed_at, :utc_datetime_usec
    end

    create index(:curation_inbox_items, [:user_id, :is_bookmarked], where: "is_bookmarked = true")

    alter table(:curation_sources) do
      add :total_items_fetched, :bigint, null: false, default: 0
      add :total_items_curated, :bigint, null: false, default: 0
      add :total_items_rejected, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:curation_sources) do
      remove :total_items_rejected
      remove :total_items_curated
      remove :total_items_fetched
    end

    drop_if_exists index(:curation_inbox_items, [:user_id, :is_bookmarked])

    alter table(:curation_inbox_items) do
      remove :dismissed_at
      remove :bookmarked_at
      remove :is_bookmarked
      remove :relevance_score
    end
  end
end
