defmodule MagusWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :magus

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_magus_key",
    signing_salt: "2nsWBZN0",
    encryption_salt: "kn0wl3dg3-oauth-enc",
    same_site: "Lax"
  ]

  def session_options, do: @session_options

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Channels for the SvelteKit workbench and future native/CLI clients.
  # Token-authenticated (see MagusWeb.UserSocket), so no session needed.
  socket "/socket", MagusWeb.UserSocket,
    websocket: true,
    longpoll: false

  # SPA build (SvelteKit, base "/"): hashed assets live under /_app and the
  # static files (service worker, icons, manifest, favicon) at the root. Served
  # from the SPA's own build dir, ahead of Phoenix's static so the SPA's
  # favicon/manifest/icons take precedence over the classic ones.
  plug Plug.Static,
    at: "/",
    from: {:magus, "priv/static/next"},
    gzip: not code_reloading?,
    only: ~w(_app service-worker.js favicon.svg icons manifest.webmanifest)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :magus,
    gzip: not code_reloading?,
    only: MagusWeb.static_paths()

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    #   plug AshAi.Mcp.Dev,
    #     # For many tools, you will need to set the `protocol_version_statement` to the older version.
    #     protocol_version_statement: "2024-11-05",
    #     otp_app: :magus,
    #     path: "/ash_ai/mcp"

    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :magus
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  if Application.compile_env(:magus, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  plug Plug.Parsers,
    # Multipart limit covers /rpc/upload (UploadHelpers.max_file_size is
    # 50MB; LiveView uploads bypass Plug.Parsers entirely).
    parsers: [:urlencoded, {:multipart, length: 60_000_000}, :json, AshJsonApi.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Cache raw body for Stripe webhook signature verification
    body_reader: {MagusWeb.Plugs.RawBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MagusWeb.Router
end
